### ISSUE TITLE
Fallout 4 cant deploy

### ISSUE THREAD

**Issue by tetoNidan** [rockerbacon/lutris-skyrimse-installers#1]
So a couple days ago I decided to try it out. I have Skyrim and Fallout 4. Both were installed before Vortex. Both are installed on the same external HD. I decided to mod Skyrim first. Works like a charm. Great job by the way. Then I added Fallout 4 and tried to mod. Im getting the dreaded:

 Deployment Failed
1488 files were not correctly deployed (see log for details)
The most likely reason is the files were locked by an external application. please...

Im sure you have seen this before. 

I have downloaded the symlinks.sh and run it inside the vortex prefix (It was not there, dont know if it was supposed to be or not) but that did not fix deployment.

I switched back and forth from skyrim and back to fallout4 a few times redeploying skyrim mods each time but that did not work either. I also tried the (Move Deployment: experimental) deployment method but that failed to.

I checked the vortex log and saw that pfx/drive_c/users/steamuser/My Documents/My Games/Fallout4/Fallout4Cuctom.ini was not being built. Wasn't even there so I created it and tried again. No luck. I checked to make sure the fallout4 folder and its contents were all owned by $USER and they are all mine and not root. 

One thing I did do to my Vortex prefix was adjusting my internet connection to use a bogus proxy. When I read that you cannot update Vortex and clicked OK and turned off what you asked in settings I thought I'd take it a step further and just disable internet connection completely so I wouldn't have the possibility of hitting the wrong button.

Any way thanks for the hard work. 
I dont know what other info you might need me to provide.

**Comment by rockerbacon** [comment]
Hi,

Sadly I could not test every game as I only own Skyrim and Skyrim SE. Some games use different names for each of its folders and I've only accounted for that on games fellow Reddit members helped me test.

From your post I can already see that one of the folder names was wrong. Please provide the output of the following commands so I can fix the symlinks script:

1. bash ~/Games/vortex-mod-manager/config_scripts/vortex-symlinks.sh
2. ls "$HOME/.steam/steam/steamapps/compatdata/377160/pfx/drive_c/users/steamuser/Local Settings/Application Data"

**Comment by tetoNidan** [comment]
Hi, That was quick! Here is the output you asked for. If you would like I can be your test monkey for Fallout 4.
I can help in any way I can. I dont mind nuking Vortex and starting over at any time. I have done it a bunch. I've been working on my own wine Vortex install for weeks. Had a partially working version using dotNet_4.7.2. Could not get loot to work though so I had been sorting Skyrim by hand and python scripting. That got old which is how I found your installer.

Output from `bash vortex-symlinks.sh`:

INFO: Using Vortex prefix at "/home/my3al/Games/.Vortex"
INFO: Found games:
VSL_FALLOUT3 VSL_FALLOUT3_GOTY VSL_FALLOUT4 VSL_FALLOUT_NEWVEGAS VSL_MORROWIND VSL_OBLIVION VSL_SKYRIMSE VSL_SKYRIM
INFO: Building symlinks for VSL_FALLOUT3
INFO: gamedir="Fallout 3" APPID="22300"
WARN: Could not find VSL_FALLOUT3 installation
WARN: Could not find VSL_FALLOUT3 prefix
INFO: Building symlinks for VSL_FALLOUT3_GOTY
INFO: gamedir="Fallout 3 goty" APPID="22370"
WARN: Could not find VSL_FALLOUT3_GOTY installation
WARN: Could not find VSL_FALLOUT3_GOTY prefix
INFO: Building symlinks for VSL_FALLOUT4
INFO: gamedir="Fallout 4" APPID="377160"
WARN: Could not find VSL_FALLOUT4 installation
WARN: Could not find VSL_FALLOUT4 prefix
INFO: Building symlinks for VSL_FALLOUT_NEWVEGAS
INFO: gamedir="Fallout New Vegas" APPID="22380"
WARN: Could not find VSL_FALLOUT_NEWVEGAS installation
WARN: Could not find VSL_FALLOUT_NEWVEGAS prefix
INFO: Building symlinks for VSL_MORROWIND
INFO: gamedir="Morrowind" APPID="22320"
WARN: Could not find VSL_MORROWIND installation
WARN: Could not find VSL_MORROWIND prefix
INFO: Building symlinks for VSL_OBLIVION
INFO: gamedir="Oblivion" APPID="22330"
WARN: Could not find VSL_OBLIVION installation
WARN: Could not find VSL_OBLIVION prefix
INFO: Building symlinks for VSL_SKYRIMSE
INFO: gamedir="Skyrim Special Edition" APPID="489830"
WARN: Could not find VSL_SKYRIMSE installation
WARN: Could not find VSL_SKYRIMSE prefix
INFO: Building symlinks for VSL_SKYRIM
INFO: gamedir="Skyrim" APPID="72850"
WARN: Could not find VSL_SKYRIM installation
WARN: Could not find VSL_SKYRIM prefix
INFO: Linking Nexus Mods downloads to Vortex

My Application Data is actually on an external HD. located in:

`/mnt/7c05a94a-46f2-4b3b-9a06-b682cad14bfc/SteamLibrary/steamapps/compatdata/377160/pfx/drive_c/users/steamuser/Local Settings/Application Data`

Dont know if that matters?

Output from `ls Application Data`:

Fallout4  Microsoft  openvr

I also forgot to mention that I was having problems with Vortex not having any text so I winetricked `corefonts` to fix it. I also changed the default Vortex install location, well not the location just the name. I just shortened the name to Vortex.

**Comment by rockerbacon** [comment]
Using a Steam library outside $HOME/.steam/steam or $HOME/.local/share/Steam is not officially supported, but it's easy to edit the symlink script to make it work.
I've just released an update which should fix the folder names for Fallout 4, here are the commands you'll need to execute to get things running:

1. wget https://github.com/rockerbacon/lutris-skyrimse-installers/releases/download/1.7.1/vortex-symlinks.sh
2. sed -i 's/STEAM_PROTON2_PATH="$HOME\/\.local\/share\/Steam"/STEAM_PROTON2_PATH="\/mnt\/7c05a94a-46f2-4b3b-9a06-b682cad14bfc\/SteamLibrary"/' vortex-symlinks.sh
3. chmod 774 vortex-symlinks.sh
4. mv vortex-symlinks.sh $HOME/Games/.Vortex/config_scripts/
5. bash $HOME/Games/.Vortex/config_scripts/vortex-symlinks.sh

Step 2 will do the editing the script requires, changing the variable STEAM_PROTON2_PATH to point to the library on your external HD, you can do it manually if you prefer.
LOOT works fine when installed on the same prefix as Vortex, I've also tested some other tools which are listed on the README.

**Comment by tetoNidan** [comment]
Sorry for the late response. I've been very busy travel for work. I will try your solution as soon as I can. Probably this weekend. 

Thank you sir.

**Comment by tetoNidan** [comment]
after modifying the vortex-symlinks.sh STEAM_PROTON2_PATH= I get the following:

INFO: gamedir="Fallout 4" APPID="377160"
INFO: Found installation for VSL_FALLOUT4 in "/mnt/7c05a94a-46f2-4b3b-9a06-b682cad14bfc/SteamLibrary/steamapps/common/Fallout 4"
INFO: Found prefix for VSL_FALLOUT4 in "/mnt/7c05a94a-46f2-4b3b-9a06-b682cad14bfc/SteamLibrary/steamapps/compatdata/377160/pfx"

Skyrim is now found as well.

Everything seems to be set right. Skyrim modding still works. Fallout 4 still fails. Something doesn't seem right. Before I installed your version of Vortex I tried to completely purge wine and everything related to it. I was pretty thorough. I didn't want any lingering settings anywhere. I removed everything in $USER related to wine. So when I installed your version of vortex and added skyrim everything worked right out of the box without having the correct path set even for skyrim as you can see from my previous post. The one plaice I didn't think to look was in my skyrim prefix. I was thinking that maybe there was something Vortex setup inside the Skyrim prefix itself with the locations needed that is not allowing your modifications to work right and allowed Vortex to work with Skyrim. I did look in the skyrim prefix and there were files from Vortex in Application Data in both users steamuser and $USER. Does my logic seem right? 

If it does one thing I could do is remove your Vortex. Rebuild the prefix in offline mode to make suer steam has a fresh prefix, manually move my saved games back. Install your Vortex and test.

**Comment by rockerbacon** [comment]
How you have added the games to Vortex? Without the proper symlinks you should have seen no games in GAMES > DISCOVERED within Vortex.

Have you by any chance changed the Wine prefix for Vortex in Lutris? Right click Vortex > Configure > Game Options > Wine Prefix, should have the value "/home/my3al/Games/.Vortex"

**Comment by tetoNidan** [comment]
No sir, the wine prefix is "/home/my3al/Games/.Vortex". 

I added the games by manually selecting the game location in vortex. That's just how I have always done it. I have never had Vortex discover any games on it's own. Because of my misunderstanding about how your program required games to be installed on steams default game install folder I didn't expect it to be able to autodetect games. 

Also I have had many versions of Vortex working with skyrim installed in a prefix I had built for Adobe Master Collection for quite a long time before an update broke it. Then I started on my quest to build my own wineprefix for vortex that I couldnt get loot to work in. That is why I was thinking that one of my attempts to install vortex had left some config files in steam's prefix that when I installed your version it may have found when I added skyrim. But I dont really know. Just a guess.

**Comment by TheRealDannyBoy** [comment]
I've found that I only get this error when the game and Vortex are on separate partitions.  All of my Steam games (I have my Steam library on a separate "games" partition mounted in `/opt`), which at this time is Morrowind, Oblivion, and SSE, give me this error, but The Witcher 3, which I installed on my `/home` partition along with my few Lutris games and Vortex, worked fine.  Copying Morrowind's game folder to my home directory and setting it manually also produced no errors when deploying.  It should be noted that these partitions are LVM logical volumes.

**Comment by rockerbacon** [comment]
@TheRealDannyBoy Have you followed the instructions form my previous comment to get the symlinks build for your custom library folder? Can you confirm your user has read, write and execute permissions to the game folders? If yes to both answers see if creating a [bind mount](https://backdrift.org/how-to-use-bind-mounts-in-linux) in your /home partition pointing to your games partition can fix the issue.

**Comment by TheRealDannyBoy** [comment]
I do have read, write, and execute permissions for all games, although I do have to use ACL's (shared computer with shared Steam library.)  For The Witcher 3 and the custom Morrowind folder, I didn't use the symlinks---I just set the path manually.

**Comment by rockerbacon** [comment]
Manually adding the path inside Vortex without building the symlinks is assured to fail

**Comment by tetoNidan** [comment]
Adding manually worked for Skyrim. Although I think I have a special case. Sorry I haven't nuked and started over yet. Been busy trying to actually complete Skyrim for the first time. Fallout got pushed to the back burner because of the sound problem and fix I used broke the use steam controller in game. Wanted to try the other sound fix but Skyrim man!

**Comment by tetoNidan** [comment]
So I just got around to nuking the skyrim pfx and re-downloading your Vortex installer. Updated the correct path in the bash script to external drive. Skyrim was discovered just fine before I ran the bash script I checked before I edited your bash script. After I ran the bash script Fallout 4 can be manually discovered discovered. I cant figure out why skyrim is found before the bash script is run but it seems that everything is working as expected. Haven't tried to mod yet either yet but will try tomorrow and update.

**Comment by tetoNidan** [comment]
Mods fail to deploy for both skyrim and fallout 4. Going to try to install your vortex prefix to the external hard drive. Also the vortex install really needs corefonts. It will fix vortex not displaying any words.

**Comment by tetoNidan** [comment]
Installing to Vortex prefix to same external hard drive that the games are installed on works. Mod deployments are working. Skyrim was in discovered already again. Manually adding Fallout works. Loot does not work at all. Any ideas?

**Comment by tetoNidan** [comment]
Got loot working by changing the "Wine Version" under Lutris runner options from "tkg-4.0_x86_64" to "WineHQ staging (4.12(staging))".

**Comment by tetoNidan** [comment]
Installing to external HD will brick FNIS and BodySlide. This probably wont be a workable solution, at least not for me. 

FNIS gives this error: ERROR(5): Cannot open Service Control Manager on computer '.'. This operation might require other privileges. 

BodySlide and outfitStudio wont load mesh shapes.

**Comment by rockerbacon** [comment]
LOOT worked out of the box for me when I installed, but I just saw they released a new version 2 days ago. Can you confirm you're using version 0.14.5?

BodySlide and OutfitStudio not loading certain assets is a problem that also happens on windows, generally with textures. There's a setting which allows you to point to where the assets are and that should fix it, I just don't remember where that setting is.

The FNIS error is a message you get when Windows needs Administrator privileges, so you may need to run FNIS as admin.

I've tried adding corefonts before but Lutris is a little finicky with Winetricks, I remember adding corefonts to the installer lead to getting errors regarding the Windows version, but I'll see if I can get it working. For the Wine version there's not much I can do because the version you're using is from a local Wine installation and not from Lutris. I'm still waiting for Lutris to update Wine so I can also update Vortex as the latest version is supposed to work on Wine +4.10 according to a Reddit user.

I'll add the requirement of having Vortex and the games on the same drive to the readme.

**Comment by rockerbacon** [comment]
As the problem seems to be fixed by having Vortex and the games installed on the same drive I'll be closing this issue. @tetoNidan I'll open the corefonts issue and I'd appreciate if you could open the LOOT issue detailing which version you're using and the behavior of the application, in case you cannot get Bodyslide and Outfit studio to work after looking in the aforementioned setting feel free to open an issue on that too.
