### ISSUE TITLE
MO2 CTD on startup: TBD_1.3.11 not found followed by segmentation fault

### ISSUE THREAD

**Issue by Daktal** [rockerbacon/lutris-skyrimse-installers#101]
Installed Mod Organizer 2 for Skyrim using Lutris. MO2 crashes after launch. Found a few errors in the log but can not find a soloution for them. Also, unsure what information i need to provide that will aid in trouble shooting. Please advise. **EDIT** i just checked my Wine version and it is 3.6 I should probably update that. I am afraid deleting and reinstalling wine will bork all the programs I currently have working with it though.

Running /home/daktal/Games/mod-organizer-2/run.sh
Initial process has started with pid 19653
Game is considered started.
Searching for Steam in '/home/daktal/.local/share/Steam'
Found Steam
Searching for game in library '/home/daktal/.local/share/Steam'
Found game
Searching for 'Proton 5.*' in library '/home/daktal/.local/share/Steam'
Found Proton

PATH='/home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin:/home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/usr/bin:/home/daktal/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' \
	LD_LIBRARY_PATH='/home/daktal/.local/share/Steam/steamapps/common/Proton 5.0/dist/lib64:/home/daktal/.local/share/Steam/steamapps/common/Proton 5.0/dist/lib:/home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i368-linux-gnu:/home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib:/home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib:/home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib:/home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib:/usr/lib/i386-linux-gnu/sse2' \
	STEAM_COMPAT_DATA_PATH='/home/daktal/.local/share/Steam/steamapps/compatdata/72850' \
	SteamGameId=72850 \
	SteamAppId=72850 \
	 \
	\
	'/home/daktal/.local/share/Steam/steamapps/common/Proton 5.0/proton' run '/home/daktal/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe' 

esync: up and running.
Setting breakpad minidump AppID = 72850
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198018354869 [API loaded no]
ntlm_auth: /home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libtdb.so.1: version `TDB_1.3.11' not found (required by /usr/lib/x86_64-linux-gnu/libsmbconf.so.0)
ntlm_auth: /home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libtdb.so.1: version `TDB_1.3.0' not found (required by /usr/lib/x86_64-linux-gnu/libsmbconf.so.0)
ntlm_auth: /home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libtdb.so.1: version `TDB_1.3.0' not found (required by /usr/lib/x86_64-linux-gnu/samba/libtdb-wrap.so.0)
ntlm_auth: /home/daktal/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libgpg-error.so.0: no version information available (required by /lib/x86_64-linux-gnu/libgcrypt.so.20)
wine: Unhandled page fault on read access to 0000000000000020 at address 00007F638B7F0AC8 (thread 00d4), starting debugger...
Unhandled exception: page fault on read access to 0x00000020 in 64-bit code (0x00007f638b7f0ac8).
Register dump:
 rip:00007f638b7f0ac8 rsp:000000000021ca50 rbp:000000000021cb60 eflags:00010206 (  R- --  I   - -P- )
 rax:0000000000000000 rbx:00007f637b6cc740 rcx:00007f637b8e7728 rdx:0000000000000003
 rsi:0000000000000000 rdi:00007f637b6c1768  r8:0000000000000018  r9:0000000000000004 r10:000000007ccad440
 r11:0000000000000008 r12:0000000000000006 r13:00007f637b6c21b8 r14:000000007ccad440 r15:0000006e00000006
Stack dump:
0x000000000021ca50:  00007f638b21ab80 00007f638b7f2618
0x000000000021ca60:  0000000000000001 0000000000000000
0x000000000021ca70:  000000000021cb30 0000000000000000
0x000000000021ca80:  0000000000000000 0000000000000000
0x000000000021ca90:  00007f637b6c2de8 000000007ccae120
0x000000000021caa0:  000000000021caf0 00007f637b6c1000
0x000000000021cab0:  00007f637b6c3866 00007f637b6c1768
0x000000000021cac0:  00007f637b8e6ef8 00007f637b6cca28
0x000000000021cad0:  0000000000000002 000000000021cb88
0x000000000021cae0:  00007f637b6c21b8 0000000300000002
0x000000000021caf0:  00007f637b6c3ab8 0000000000008f70
0x000000000021cb00:  00000000000005db 0000000000000000
Backtrace:
=>0 0x00007f638b7f0ac8 _dl_find_dso_for_object+0xffffffffffffffff() in ld-linux-x86-64.so.2 (0x000000000021cb60)
  1 0x00007f638b21ab80 xdr_uint64_t+0x28d48f() in libc.so.6 (0x000000000021cb60)
  2 0x00007f638b7f2618 _dl_find_dso_for_object+0xffffffffffffffff() in ld-linux-x86-64.so.2 (0x000000000021cb60)
0x00007f638b7f0ac8 _dl_find_dso_for_object+0xffffffffffffffff in ld-linux-x86-64.so.2: movl	0x0000000000000008(%r8),%esi
Modules:
Module	Address					Debug info	Name (177 modules)
PE	          220000-         59be000	Deferred        qt5webenginecore
PE	         59c0000-         5d6e000	Deferred        qt5quick
PE	         5d70000-         615f000	Deferred        qt5qml
PE	         6160000-         62ad000	Deferred        qt5network
PE	         62b0000-         6877000	Deferred        qt5core
PE	         6880000-         6884000	Deferred        api-ms-win-crt-heap-l1-1-0
PE	         6890000-         6ec6000	Deferred        qt5gui
PE	         6ed0000-         6ef1000	Deferred        qt5webchannel
PE	         6f00000-         6f52000	Deferred        qt5positioning
PE	         6f70000-         7235000	Deferred        d3d11
PE	         7240000-         7292000	Deferred        qt5printsupport
PE	         72a0000-         77f8000	Deferred        qt5widgets
PE	         7800000-         7816000	Deferred        qt5quickwidgets
PE	         7820000-         784a000	Deferred        qt5websockets
PE	         7850000-         799a000	Deferred        uibase
PE	         79a0000-         7a2e000	Deferred        qt5winextras
PE	         7a30000-         7beb000	Deferred        usvfs_x64
PE	         7bf0000-         7c0e000	Deferred        liblz4
PE	         83c0000-         83c4000	Deferred        api-ms-win-core-localization-l1-2-1
PE	         83d0000-         853f000	Deferred        qwindows
PE	         8540000-         85d7000	Deferred        openvr_api_dxvk
PE	        61540000-        61544000	Deferred        api-ms-win-crt-locale-l1-1-0
PE	        61f40000-        61f44000	Deferred        wtsapi32
PE	        620c0000-        620c4000	Deferred        api-ms-win-crt-filesystem-l1-1-0
PE	        62140000-        62145000	Deferred        uxtheme
PE	        62240000-        624c8000	Deferred        d3d9
PE	        62600000-        62604000	Deferred        usp10
PE	        63140000-        63145000	Deferred        api-ms-win-crt-runtime-l1-1-0
PE	        637c0000-        6383f000	Deferred        winmm
PE	        638c0000-        638c5000	Deferred        dwmapi
PE	        64340000-        64347000	Deferred        winhttp
PE	        64500000-        64509000	Deferred        concrt140
PE	        64940000-        64945000	Deferred        shcore
PE	        64b80000-        64b85000	Deferred        hid
PE	        64d40000-        64d47000	Deferred        vulkan-1
PE	        65000000-        6502c000	Deferred        ole32
PE	        65780000-        65785000	Deferred        version
PE	        66440000-        6644a000	Deferred        msacm32
PE	        66a80000-        66aa8000	Deferred        msvcp140
PE	        67d00000-        67d04000	Deferred        userenv
PE	        68a40000-        68a4f000	Deferred        shlwapi
PE	        68ac0000-        68ac4000	Deferred        api-ms-win-crt-time-l1-1-0
PE	        69380000-        69385000	Deferred        api-ms-win-crt-stdio-l1-1-0
PE	        69b80000-        69b84000	Deferred        api-ms-win-crt-environment-l1-1-0
PE	        6a100000-        6a10d000	Deferred        oleaut32
PE	        6a4c0000-        6a4c4000	Deferred        api-ms-win-crt-utility-l1-1-0
PE	        6a700000-        6a717000	Deferred        setupapi
PE	        6b2c0000-        6b2e2000	Deferred        wininet
PE	        6b6c0000-        6b76d000	Deferred        comdlg32
PE	        6b880000-        6b884000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	        6bec0000-        6bec6000	Deferred        imm32
PE	        6c240000-        6c244000	Deferred        dxva2
PE	        6d580000-        6d585000	Deferred        api-ms-win-crt-convert-l1-1-0
PE	        6d9c0000-        6d9cd000	Deferred        mpr
PE	        6dd80000-        6dd85000	Deferred        api-ms-win-crt-string-l1-1-0
PE	        6e280000-        6e285000	Deferred        ncrypt
PE	        6e340000-        6e344000	Deferred        api-ms-win-core-synch-l1-2-0
PE	        6e6c0000-        6e715000	Deferred        comctl32
PE	        6eac0000-        6eac4000	Deferred        vcruntime140
PE	        6eb00000-        6eb06000	Deferred        wintab32
PE	        6fbc0000-        6fbcb000	Deferred        rpcrt4
PE	        6ff40000-        6ff4e000	Deferred        vcruntime140_1
PE	        70580000-        70586000	Deferred        api-ms-win-crt-math-l1-1-0
PE	        70a00000-        70a04000	Deferred        dhcpcsvc
PE	        71140000-        71154000	Deferred        urlmon
PE	        71240000-        71246000	Deferred        jsproxy
ELF	        7a800000-        7aa0a000	Deferred        opengl32<elf>
  \-PE	        7a850000-        7aa0a000	\               opengl32
PE	        7b000000-        7b013000	Deferred        kernelbase
ELF	        7b400000-        7b682000	Deferred        kernel32<elf>
  \-PE	        7b410000-        7b682000	\               kernel32
ELF	        7bc00000-        7bf19000	Deferred        ntdll<elf>
  \-PE	        7bc20000-        7bf19000	\               ntdll
ELF	        7c000000-        7c003000	Deferred        <wine-loader>
PE	       140000000-       1405e8000	Deferred        modorganizer
PE	       180000000-       18003f000	Deferred        qt5webenginewidgets
ELF	    7f637994b000-    7f637b6c1000	Deferred        libnvidia-glcore.so.440.100
ELF	    7f637b6c1000-    7f637b8e8000	Deferred        libtinfo.so.5
ELF	    7f637b8e8000-    7f637bb1f000	Deferred        libedit.so.2
ELF	    7f637d506000-    7f6381f53000	Deferred        libllvm-10.so.1
ELF	    7f6382268000-    7f638246c000	Deferred        libnvidia-tls.so.440.100
ELF	    7f638246c000-    7f638277e000	Deferred        libglx_nvidia.so.0
ELF	    7f638287f000-    7f6382adc000	Deferred        libvulkan.so.1
ELF	    7f6382adc000-    7f6382af8000	Deferred        kerberos<elf>
  \-PE	    7f6382ae0000-    7f6382af8000	\               kerberos
ELF	    7f6382af8000-    7f6382cfc000	Deferred        libkeyutils.so.1
ELF	    7f6382cfc000-    7f6382f41000	Deferred        libdbus-1.so.3
ELF	    7f6382f41000-    7f638314a000	Deferred        libkrb5support.so.0
ELF	    7f638314a000-    7f638334e000	Deferred        libcom_err.so.2
ELF	    7f638334e000-    7f6383577000	Deferred        libk5crypto.so.3
ELF	    7f6383577000-    7f638384a000	Deferred        libkrb5.so.3
ELF	    7f638384a000-    7f6383a5b000	Deferred        libavahi-client.so.3
ELF	    7f6383a5b000-    7f6383c68000	Deferred        libavahi-common.so.3
ELF	    7f6383c68000-    7f6383ea7000	Deferred        libgssapi_krb5.so.2
ELF	    7f6383ea7000-    7f63840fb000	Deferred        libcups.so.2
ELF	    7f63840fd000-    7f6384303000	Deferred        libxfixes.so.3
ELF	    7f6384303000-    7f638450d000	Deferred        libxcursor.so.1
ELF	    7f638450d000-    7f638471d000	Deferred        libxi.so.6
ELF	    7f638471d000-    7f6384920000	Deferred        libxcomposite.so.1
ELF	    7f6384920000-    7f6384b2a000	Deferred        libxrandr.so.2
ELF	    7f6384b2a000-    7f6384d34000	Deferred        libxrender.so.1
ELF	    7f6384d34000-    7f6384f39000	Deferred        libxxf86vm.so.1
ELF	    7f6384f39000-    7f638513c000	Deferred        libxinerama.so.1
ELF	    7f638513c000-    7f6385342000	Deferred        libxdmcp.so.6
ELF	    7f6385342000-    7f6385546000	Deferred        libxau.so.6
ELF	    7f6385546000-    7f6385766000	Deferred        libxcb.so.1
ELF	    7f6385766000-    7f6385aa1000	Deferred        libx11.so.6
ELF	    7f6385aa1000-    7f6385cb3000	Deferred        libxext.so.6
ELF	    7f6385cb3000-    7f6385d7f000	Deferred        winex11<elf>
  \-PE	    7f6385cc0000-    7f6385d7f000	\               winex11
ELF	    7f6385d7f000-    7f6385f87000	Deferred        libffi.so.6
ELF	    7f6385f87000-    7f6386201000	Deferred        libgmp.so.10
ELF	    7f6386201000-    7f6386435000	Deferred        libhogweed.so.4
ELF	    7f6386435000-    7f638666b000	Deferred        libnettle.so.6
ELF	    7f638666b000-    7f638687e000	Deferred        libtasn1.so.6
ELF	    7f638687e000-    7f6386ab2000	Deferred        libidn.so.11
ELF	    7f6386ab2000-    7f6386d15000	Deferred        libp11-kit.so.0
ELF	    7f6386d15000-    7f638704e000	Deferred        libgnutls.so.30
ELF	    7f638715b000-    7f6387385000	Deferred        libexpat.so.1
ELF	    7f6387385000-    7f63875bb000	Deferred        libfontconfig.so.1
ELF	    7f63875bb000-    7f63877d2000	Deferred        libz.so.1
ELF	    7f63877d2000-    7f6387a70000	Deferred        libfreetype.so.6
ELF	    7f6387a70000-    7f6387b9d000	Deferred        msvcr120<elf>
  \-PE	    7f6387aa0000-    7f6387b9d000	\               msvcr120
ELF	    7f6387b9d000-    7f6387bf4000	Deferred        winevulkan<elf>
  \-PE	    7f6387bb0000-    7f6387bf4000	\               winevulkan
ELF	    7f6387bf4000-    7f6387d98000	Deferred        wined3d<elf>
  \-PE	    7f6387c10000-    7f6387d98000	\               wined3d
ELF	    7f6387d98000-    7f6387ddf000	Deferred        dxgi<elf>
  \-PE	    7f6387da0000-    7f6387ddf000	\               dxgi
ELF	    7f6387ddf000-    7f6387e86000	Deferred        dwrite<elf>
  \-PE	    7f6387df0000-    7f6387e86000	\               dwrite
ELF	    7f6387e86000-    7f6387ed7000	Deferred        secur32<elf>
  \-PE	    7f6387e90000-    7f6387ed7000	\               secur32
ELF	    7f6387ed7000-    7f6387f54000	Deferred        dbghelp<elf>
  \-PE	    7f6387ee0000-    7f6387f54000	\               dbghelp
ELF	    7f6387f54000-    7f6387fb2000	Deferred        winspool<elf>
  \-PE	    7f6387f60000-    7f6387fb2000	\               winspool
ELF	    7f6387fb2000-    7f6387fd9000	Deferred        bcrypt<elf>
  \-PE	    7f6387fc0000-    7f6387fd9000	\               bcrypt
ELF	    7f6387fd9000-    7f63880e1000	Deferred        crypt32<elf>
  \-PE	    7f6387ff0000-    7f63880e1000	\               crypt32
ELF	    7f63880e1000-    7f63882fc000	Deferred        libresolv.so.2
ELF	    7f63882fc000-    7f6388324000	Deferred        dnsapi<elf>
  \-PE	    7f6388300000-    7f6388324000	\               dnsapi
ELF	    7f6388324000-    7f638845f000	Deferred        ucrtbase<elf>
  \-PE	    7f6388350000-    7f638845f000	\               ucrtbase
ELF	    7f638845f000-    7f63884a1000	Deferred        ws2_32<elf>
  \-PE	    7f6388470000-    7f63884a1000	\               ws2_32
ELF	    7f63884a1000-    7f63884d4000	Deferred        iphlpapi<elf>
  \-PE	    7f63884b0000-    7f63884d4000	\               iphlpapi
ELF	    7f63884d4000-    7f638851e000	Deferred        netapi32<elf>
  \-PE	    7f63884e0000-    7f638851e000	\               netapi32
ELF	    7f638851e000-    7f6388f6a000	Deferred        shell32<elf>
  \-PE	    7f6388540000-    7f6388f6a000	\               shell32
ELF	    7f6388f6a000-    7f6389056000	Deferred        msvcrt<elf>
  \-PE	    7f6388f90000-    7f6389056000	\               msvcrt
ELF	    7f6389056000-    7f638909a000	Deferred        sechost<elf>
  \-PE	    7f6389060000-    7f638909a000	\               sechost
ELF	    7f638909a000-    7f6389114000	Deferred        advapi32<elf>
  \-PE	    7f63890b0000-    7f6389114000	\               advapi32
ELF	    7f6389114000-    7f63892c4000	Deferred        gdi32<elf>
  \-PE	    7f6389130000-    7f63892c4000	\               gdi32
ELF	    7f63893c4000-    7f638964a000	Deferred        user32<elf>
  \-PE	    7f63893e0000-    7f638964a000	\               user32
ELF	    7f6389a28000-    7f6389c3a000	Deferred        libnss_files.so.2
ELF	    7f6389c3a000-    7f6389e54000	Deferred        libnsl.so.1
ELF	    7f6389e54000-    7f638a060000	Deferred        libnss_nis.so.2
ELF	    7f638a060000-    7f638a26a000	Deferred        libnss_compat.so.2
ELF	    7f638a46a000-    7f638a681000	Deferred        libgcc_s.so.1
ELF	    7f638a681000-    7f638aa1f000	Deferred        libm.so.6
ELF	    7f638aa1f000-    7f638ac27000	Deferred        librt.so.1
ELF	    7f638ac2a000-    7f638ae2e000	Deferred        libdl.so.2
ELF	    7f638ae30000-    7f638b221000	Export          libc.so.6
ELF	    7f638b221000-    7f638b440000	Deferred        libpthread.so.0
ELF	    7f638b440000-    7f638b7e2000	Export          libwine.so.1
ELF	    7f638b7e4000-    7f638ba0e000	Export          ld-linux-x86-64.so.2
Threads:
process  tid      prio (all id:s are in hex)
00000020 steam.exe
	000000a8    0
	00000024    0
00000038 services.exe
	000000a0    0
	00000098    0
	00000080    0
	0000006c    0
	00000054    0
	00000050    0
	0000004c    0
	00000040    0
	0000003c    0
00000044 winedevice.exe
	00000060    0
	0000005c    0
	00000058    0
	00000048    0
00000064 plugplay.exe
	00000074    0
	00000070    0
	00000068    0
00000078 winedevice.exe
	000000a4    0
	0000009c    0
	00000094    0
	00000090    0
	0000008c    0
	00000088    0
	00000084    0
	0000007c    0
000000ac explorer.exe
	000000c4    0
	000000c0    0
	000000b4    0
	000000b0    0
000000d0 (D) Z:\home\daktal\Games\mod-organizer-2\ModOrganizer2\ModOrganizer.exe
	000000d4    0 <==
System information:
    Wine build: wine-5.0-655-g2409bd1
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 4.15.0-108-generic
Game is considered exited.
Initial process has exited.
All monitored processes have exited.
Exit with returncode 0

**Comment by rockerbacon** [comment]
Page faults are usually related to library problems. What distro are you using?

**Comment by Daktal** [comment]
Currently using
Distro: Linux Mint 19.1 Tessa
Kernel: 4.15.0-76-generic

**Comment by Daktal** [comment]
TDB_1.3.11' not found seems to be the culprit but no amount of googling has told me how to install TDB 1.3.11

**Comment by rockerbacon** [comment]
Can you check if the problem still happens in the latest release? You will need to remove the directory `/home/daktal/.local/share/Steam/steamapps/compatdata/72850` and launch the game on Steam once before reinstalling.

**Comment by rockerbacon** [comment]
Closed due to inactivity
