### ISSUE TITLE
Any Fix for Alt-Tabbing in New Vegas?

### ISSUE THREAD

**Issue by KorgiSilvercloud** [rockerbacon/lutris-skyrimse-installers#106]
Just like that title says, I was just curios if anyone has devised a solution for alt-tabbing in New Vegas yet? Currently, when you alt-tab out of the game, it causes the game to freeze and forces you to manually kill the process. Sometimes not even that is enough and you have to restart your whole system. I know this issue is in no way related to this project in particular, but if anyone has a strategy to deal with this problem I would really like to know. I checked the protonDB page and no-one seems to have really come up with a solid solution there either...besides running the game in windowed mode, wich we cannot do in this case.

**Comment by kleshas** [comment]
[HKCU\software\Wine\X11 Driver]
UseTakeFocus="false"

This is how you do something similar with Hearthstone.  Might be worth a try.

**Comment by rockerbacon** [comment]
Alt-Tabbing not working properly is a problem in the Creation Engine itself. It also doesn't work well in Windows and you need script extender plugins to get it working.
