### ISSUE TITLE
"'%AppData%' returned empty string" when running winetricks

### ISSUE THREAD

**Issue by fang44Zen** [rockerbacon/lutris-skyrimse-installers#107]
Hello,
I still have the same problem when i try to install mod organizer 2 here is the message "Error while installing winetricks, please run Lutris from a terminal and check the logs"

And on the terminal:
"wine cmd.exe /c echo '%AppData%' returned empty string, error message "" "

I don't really understand...

**Comment by rockerbacon** [comment]
Try to reset the Steam prefix for the game:
1. Delete `<steam library>/steamapps/compatdata/<game appid>`
2. Ensure the game is configured to use Proton 5
3. Launch the game on Steam so it runs first time setup again
4. Try to use the installer again

If you don't know where the Steam library is then it's probably `$HOME/.steam/root/steam`. For the game appid check [here](https://github.com/rockerbacon/lutris-skyrimse-installers/tree/master/gamesinfo).

**Comment by rockerbacon** [comment]
Closed due to inactivity
