### ISSUE TITLE
Installer stuck running Winetricks

### ISSUE THREAD

**Issue by kleshas** [rockerbacon/lutris-skyrimse-installers#108]
new arch install.  Fresh compatdata and skyrimse install.  winetricks --self-update run and the good vcrun files in the cache.
last lines of modorganizer.yml install:

0738:fixme:advapi:RegisterEventSourceW ((null),L".NET Runtime Optimization Service"): stub
0738:fixme:advapi:DeregisterEventSource (0xcafe4242) stub
03fc:err:ole:CoReleaseMarshalData StdMarshal ReleaseMarshalData failed with error 0x8001011d
028c:fixme:advapi:RegisterEventSourceW ((null),L".NET Runtime Optimization Service"): stub
028c:fixme:advapi:DeregisterEventSource (0xcafe4242) stub
04c0:err:ntdll:RtlpWaitForCriticalSection section 7BCD0520 "../../../wine-staging/dlls/ntdll/loader.c: fls_section" wait timed out in thread 04c0, blocked by 04d4, retrying (60 sec)

Earlier on in the install it complained that the install was in a 64 bit prefix and that dotnet48 and dotnet40 may not fully work.

Google indicates dotnet should be installed in 32bit prefix.

**Comment by kleshas** [comment]
Tried 2.7.5 (wiped cache, lutris instance, compatdata).  Installs fine, but doesn't run MO2 unless --wined3d used as an argument in run.sh.  But then the game doesn't run from MO2 (though LOOT etc do).

**Comment by kleshas** [comment]
Got it working on 2.7.5 - disabled the "disable Lutris runtime" in lutris properties.  Will try with 2.8.2

**Comment by rockerbacon** [comment]
This might be caused by a mismatch in the libraries required by `dotnet48`. I have never ran into this before and `dotnet48` is the Winetricks verb I use the most when experimenting things.
