### ISSUE TITLE
SKSE Missing

### ISSUE THREAD

**Issue by LuxLucian** [rockerbacon/lutris-skyrimse-installers#109]
After installing and booting MO does not have a option for SKSE and fails to start Skyrim SE. It returns "Application load error 3:0000065432

**Comment by rockerbacon** [comment]
What Linux distribution are you using?

**Comment by LuxLucian** [comment]
Solus Budgie 4.1

**Comment by rockerbacon** [comment]
This is an odd issue. Can you try reseting the prefix and reinstalling the [latest release](https://github.com/rockerbacon/lutris-skyrimse-installers/releases/tag/2.8.3)? If the problem continues, please provide the logs from the installation process.

To reset the prefix:
1. Delete the directory `<steam library>/steamapps/compatdata/489830`
2. Run the game on Steam so it runs first time setup again

**Comment by LuxLucian** [comment]
Sorry for the long wait, I'll get to it asap.

**Comment by LuxLucian** [comment]
Installing again seemed to fix the issue of SKSE not installing, but the installer assumed my directory was in a deleted Steam library folder. The actual location of the game is in my main Steam install, on the home drive.

**Comment by LuxLucian** [comment]
Doing another install fixed it. I think it was my bad when setting up MO. Thanks for the help!
