### ISSUE TITLE
Installation hangs at "01a4:fixme:advapi:DeregisterEventSource (0xcafe4242) stub"

### ISSUE THREAD

**Issue by hazelnot** [rockerbacon/lutris-skyrimse-installers#110]
Possibly related to #108 .

I'm running it on Arch, and it's worked before on another install and an older version of this script.

I attached the log, hope it helps.

[lutris log.txt](https://github.com/rockerbacon/lutris-skyrimse-installers/files/4892229/lutris.log.txt)

**Comment by kleshas** [comment]
Yeah, that's the same log I get in #108

**Comment by rockerbacon** [comment]
This will be discussed in #108
