### ISSUE TITLE
Mod Organizer 2 does not launch

### ISSUE THREAD

**Issue by data4pass** [rockerbacon/lutris-skyrimse-installers#118]
The application installed (from the lutris.net page) without any errors or problems, but whenever I try to launch it, it closes immediately.

**Log**:

> Running /home/data4pass/.local/share/Steam/steamapps/common/Proton 5.0/dist/bin/wine /home/data4pass/Games/mod-organizer-2/run.sh
Initial process has started with pid 7633
Game is considered started.
wineserver: using server-side synchronization.
Game is considered exited.
Initial process has exited.
All monitored processes have exited.
Exit with returncode 12032

I should say that initially the `Wine prefix` field after installation was empty, so I manually added my New Vegas's `pfx` directory:
>/home/data4pass/.local/share/Steam/steamapps/compatdata/22380/pfx/

Looking at similar issues (#111 and #115) it seems like I need to have Mono 5.1.0 and vcredist2019 installed, but checking via winetricks's `Add/Remove Programs` I noticed that both have already been installed:

![ss](https://user-images.githubusercontent.com/28884686/87852098-a1010300-c931-11ea-9470-95e7aad9e38f.png)

I'm not sure what else there is to do to have the application launch. I appreciate any help given. Thank you!

**My specs**:

- OS: Ubuntu 19.10 x86_64
- Kernel: 5.3.0-62-generic
- CPU: Intel Pentium 2020M (2) @ 2.400GHz
- GPU: Intel(R) Ivybridge Mobile
- RAM: 9862MiB
- Lutris version: 0.5.7
- Proton vesion: 5.0-9

**Comment by LithianFI** [comment]
In both of the issues you tagged the system was running Arch Linux. Ubuntu installation should probably not have Mono and have .Net 4.0 instead, which is also what the installer should be doing by default.

Installer on the Lutris page is several releases behind, try using the most recent installation from this github page [](https://github.com/rockerbacon/lutris-skyrimse-installers/releases/tag/2.8.3) and see it that fixes the issue.

**Comment by rockerbacon** [comment]
> Ubuntu installation should probably not have Mono and have .Net 4.0 instead, which is also what the installer should be doing by default.

Steam installs Mono when it creates the prefix, that's unlikely to be the issue.

**Comment by rockerbacon** [comment]
The script is not even starting because it's not being launched correctly.

It should be run directly:
```bash
/home/data4pass/Games/mod-organizer-2/run.sh
```

But instead it is being run with Proton:
```bash
/home/data4pass/.local/share/Steam/steamapps/common/Proton 5.0/dist/bin/wine /home/data4pass/Games/mod-organizer-2/run.sh
```

Did you get the installer directly from Lutris?

**Comment by rockerbacon** [comment]
Just checked, the installer on Lutris.net is configured to use a Wine runner but it should be using a Linux runner instead.

From the [README](https://github.com/rockerbacon/lutris-skyrimse-installers):

> While these installers may be available on Lutris.net, users are always recommended to use the latest stable release from this repository. The testers and maintainers of this project have little control over the content on Lutris and cannot assure that the installers available there are up to date nor that they haven't been incorrectly modified.

**Comment by data4pass** [comment]
Ah, thank you. Yeah I've reinstalled MO2 by using the latest version of the install script, but the application still won't launch ([logs](https://github.com/rockerbacon/lutris-skyrimse-installers/files/4941783/log.txt)).

After noticing this error at the bottom part of the logs:
```
Z:\home\data4pass\Games\mod-organizer-2\ModOrganizer2\ModOrganizer.exe: symbol lookup error: /lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: xcb_dri3_get_supported_modifiers
```

I googled around, found [this](https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1799442) and followed comment 4's suggestion by adding `/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0` to the `LD_PRELOAD` environment variable (through Configure > System Options). After running MO2 again, that part then changed to:

```
Z:\home\data4pass\Games\mod-organizer-2\ModOrganizer2\ModOrganizer.exe: symbol lookup error: /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0: undefined symbol: xcb_send_request_with_fds
```

From [this issue](https://github.com/ValveSoftware/steam-for-linux/issues/5249#issuecomment-345331195) I added another path to the `LD_PRELOAD` variable and added `LIBGL_DRI3_DISABLE=1`. So apparently I had to add:

```
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0:/usr/$LIB/libstdc++.so.6
LIBGL_DRI3_DISABLE=1
```

to the environment variables option. MO2 now runs, but running `FalloutNV.exe` through MO2 fails ([logs](https://github.com/rockerbacon/lutris-skyrimse-installers/files/4941837/log2.txt)), even though I can run New Vegas fine directly from Steam.

I'm not sure if this will help but I'll paste it:

``` 
$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 19.2.8
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 19.2.8
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 19.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

Thank you again.

**Comment by rockerbacon** [comment]
@data4pass since the problem is different I've moved it to another issue
