### ISSUE TITLE
MO2 Won't launch - libgamemodeauto.so.0 "LD_PRELOAD cannot be preloaded"

### ISSUE THREAD

**Issue by nikolaos-spyratos** [rockerbacon/lutris-skyrimse-installers#119]
Hi there,

Firstly, thanks for this project. Definitely saving gaming efforts out there.

I seem to be having some issue with LD_PRELOAD on Mod Organizer 2. My log is:

```
Running gamemoderun /home/thecapegreek/.local/share/lutris/runners/wine/lutris-5.7-5-x86_64/bin/wine /media/thecapegreek/BenSwolo/Games/Mods/Skyrim/Tools/modorganizer2/run.sh
Initial process has started with pid 84016
Game is considered started.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Game is considered exited.
Initial process has exited.
All monitored processes have exited.
Exit with returncode 12032
```

Tried searching reddit but only found some people getting similar issues for WoW/Battle.net games. No idea if it would have any effect but I also tried adding `LD_PRELOAD=$LD_PRELOAD:/usr/\$LIB/libgamemodeauto.so` before the rest of the command in the run.sh file but that didn't help.

Any idea where to look next on this?

**Comment by rockerbacon** [comment]
> Running gamemoderun /home/thecapegreek/.local/share/lutris/runners/wine/lutris-5.7-5-x86_64/bin/wine /media/thecapegreek/BenSwolo/Games/Mods/Skyrim/Tools/modorganizer2/run.sh

Looks like you got the installer from Lutris.net instead of getting it from this repo, see #118.

If you have any problems after getting the correct installer, feel free to open another issue.

**Comment by nikolaos-spyratos** [comment]
Fair enough, Saw that installer having some references to this repo and had Lutris hanging on extractions using the direct one, but I'll try again.

**Comment by SmiVan** [comment]
Just a note for future readers - `libgamemodeauto.so.0 "LD_PRELOAD cannot be preloaded"` probably cannot be a cause for launching issues - as it occurs even in normal behaviour.
