### ISSUE TITLE
Script doesn't detect Fallout: New Vegas

### ISSUE THREAD

**Issue by ptkato** [rockerbacon/lutris-skyrimse-installers#12]
I'm using the default steam install location, SkyrimSE is detected just fine, however New Vegas ain't.

**Comment by rockerbacon** [comment]
New Vegas was tested by a Reddit user and I remember I had to fix a few things in it.

Are you using the installer provided in this repo or installing straight from Lutris? I have not been the maintainer of this installer on Lutris.net so it's possible that someone might have broken it.

If the installer in this repo doesn't work please post the output for the command:
```
./$HOME/Games/vortex-mod-manager/config_scripts/vortex-symlinks.sh
```

**Comment by ptkato** [comment]
I tried the installer from here and from Lutris, neither work.

Note that modding works just fine if I add the game folder manually.
