### ISSUE TITLE
Unhandled exception crash on launch

### ISSUE THREAD

**Issue by yaomtc** [rockerbacon/lutris-skyrimse-installers#121]
Here is the output:

[mod-organizer-2-crash.txt](https://github.com/rockerbacon/lutris-skyrimse-installers/files/4951270/mod-organizer-2-crash.txt)

Skyrim Special Edition was installed and run before installing Mod Organizer 2, and Steam is configured to use Proton 5.0-9.

This is on Arch.

**Comment by LithianFI** [comment]
See #111

**Comment by yaomtc** [comment]
Oops, my bad - didn't do a search, just kinda glanced over the issues and missed that one
