### ISSUE TITLE
Desktop entry issues preventing nxm links from being handled correctly

### ISSUE THREAD

**Issue by davidtjones** [rockerbacon/lutris-skyrimse-installers#138]
The default desktop entry located at `$HOME/.local/share/applications/modorganizer2-nxm-handler.desktop` doesn't work on my system. After a decent amount of tracing and looking at issue #92, I discovered two issues that prevented nxm links from being handled correctly. 

1. The single quotes around %u in the Exec key value were preventing the URL from being correctly interpolated. Removing these allowed `xdg-open "nxm://..."` to properly function. 
2. The MimeType key values prevented firefox from directing nxm links to mod organizer. I stumbled upon [this thread ](https://github.com/TanninOne/modorganizer/issues/463#issuecomment-349643462) from the original mod organizer. After removing the nxm-protocol handler and then downloading a nexus mod, Firefox presented me with a "choose an application" prompt, and I was able to select mod organizer, and the mod downloaded as expected.

The final desktop entry that worked for me was:
```
[Desktop Entry]    
Type=Application    
Categories=Game;    
Exec=/home/david/.local/bin/modorganizer2-nxm-broker.sh %u    
Name=Mod Organizer 2 NXM Handler    
MimeType=x-scheme-handler/nxm;    
NoDisplay=true  
```

I am not sure why these issues affected me, as it apparently works for others. Currently running Arch Linux, I'm not sure if this is something specific to non-Ubuntu based distros.

**Comment by ale-saglia** [comment]
Thanks, solved also for me the same problem (I'm on Void Linux).

**Comment by rockerbacon** [comment]
Both changes seem harmless. I'll implement them as soon as I can.

**Comment by trevorgunn** [comment]
I'm not 100% on this but maybe Ubuntu adds `$HOME/.local/bin` to `$PATH` globally? Because I set that as my path in my `.zshrc` which is why it works from an interactive shell but I need to specify the full path in the `.desktop` file to make it work.

**Comment by davidtjones** [comment]
@trevorgunn I can confirm that $HOME/.local/bin was not on my path until I added it (on arch linux). I didn't try testing with $PATH after I had made other changes but the change that made firefox work was removing `x-scheme-handler/nxm-protocol` from the mimetype value and just leaving `x-scheme-handler/nxm`. I am unsure what the intended functionality is of the nxm-protocol.

**Comment by rockerbacon** [comment]
> I'm not 100% on this but maybe Ubuntu adds `$HOME/.local/bin` to `$PATH` globally? Because I set that as my path in my `.zshrc` which is why it works from an interactive shell but I need to specify the full path in the `.desktop` file to make it work in Firefox.

You want `$HOME/.local/bin` to be in `$HOME/.profile` instead of being in the rc of a specific shell interpreter. Most distros should do this automatically.

**Comment by tjackson** [comment]
Ubuntu has this in /etc/skel/.profile:
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

Otherwise in /etc/environment:
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

However, the exact changes davidtjones made on the ~/.local/share desktop file were necessary for me with Firefox. And even when the nxm protocol was being picked up, Mod Organizer 2 crashes with a Python error (I can't find a log) upon trying to use a Download Manager link from Nexus, so something is still borked. nxmhandler.log in compatdata/pfx doesn't show any error either.

**Comment by tjackson** [comment]
Sorry for the noise, my particular crash was my own fault, with winemenubuilder.exe disabled in my environment.

**Comment by ShneekeyTheLost** [comment]
I also found the information in the first post to be helpful, but as a more universal fix you can try the changes on two lines as follows:

```
[Desktop Entry]    
Type=Application    
Categories=Game;    
Exec=$HOME/.local/bin/modorganizer2-nxm-broker.sh %u  
Name=Mod Organizer 2 NXM Handler
MimeType=x-scheme-handler/nxm;
NoDisplay=true

```
That should function for most Linux-based systems. Doing this at least allowed me to use MO2 to download and install mods from Nexus once manually setting the API key.
