### ISSUE TITLE
Witcher 3 support

### ISSUE THREAD

**Issue by soredake** [rockerbacon/lutris-skyrimse-installers#14]
Folder is "The Witcher 3"

**Comment by rockerbacon** [comment]
Users on Reddit have reported that The Witcher 3 should work after manually adding its folder in Vortex: `Settings > Games > Add Search Directory`. That should be a good temporary solution.

All auto detection support was built with Bethesda Games in mind, which all have the same folder layout. I'll test later if the same system will work for The Witcher games as well.

In the case of those games it's also important to note that they can be installed straight from GOG and the symlink script currently only looks for games in Steam folders.

**Comment by soredake** [comment]
Yes, manually adding works fine.

**Comment by rockerbacon** [comment]
With the current focus on Mod Organizer 2 it doesn't make much sense to keep this issue open, it's highly unlikely that this will be worked on.
