### ISSUE TITLE
Error installing mod organizer

### ISSUE THREAD

**Issue by Litleck** [rockerbacon/lutris-skyrimse-installers#143]
I'm trying to install Mod Organizer 2 and every single time I end up getting this same error,

```
Game is considered started.
Searching for Steam in '/home/litleck/.steam/debian-installation'
Found Steam
Searching for Steam in '/home/litleck/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Steam not found in this install path
Searching for game in library '/home/litleck/.steam/debian-installation'
Found game
/home/litleck/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 44: return: can only `return' from a function or sourced script
ERROR: could not find game with APPID '489830'
/home/litleck/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 49: return: can only `return' from a function or sourced script
Installing script extender...
/usr/bin/bash: line 154: /home/litleck/.local/share/lutris/runtime/winetricks/winetricks: Not a directory
```

I have no idea what to do to fix it and was hoping that I could get help here.

**Comment by rockerbacon** [comment]
Lutris did not install Winetricks for some reason. This long command will download Winetricks to the correct location:

```bash
mkdir -p "$HOME/.local/share/lutris/runtime/winetricks" && curl -XGET 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' > "$HOME/.local/share/lutris/runtime/winetricks/winetricks" && chmod u+x "$HOME/.local/share/lutris/runtime/winetricks/winetricks"
```

If it complains about `curl` not being found, try with `wget`:

```bash
mkdir -p "$HOME/.local/share/lutris/runtime/winetricks" && wget -O "$HOME/.local/share/lutris/runtime/winetricks/winetricks" 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' && chmod u+x "$HOME/.local/share/lutris/runtime/winetricks/winetricks"
```

If both fail, you will need to install either `curl` or `wget` on your system.

Let me know if that solves your problem.

**Comment by Litleck** [comment]
> Lutris did not install Winetricks for some reason. This long command will download Winetricks to the correct location:
> 
> ```shell
> mkdir -p "$HOME/.local/share/lutris/runtime/winetricks" && curl -XGET 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' > "$HOME/.local/share/lutris/runtime/winetricks/winetricks" && chmod u+x "$HOME/.local/share/lutris/runtime/winetricks/winetricks"
> ```
> 
> If it complains about `curl` not being found, try with `wget`:
> 
> ```shell
> mkdir -p "$HOME/.local/share/lutris/runtime/winetricks" && wget -O "$HOME/.local/share/lutris/runtime/winetricks/winetricks" 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' && chmod u+x "$HOME/.local/share/lutris/runtime/winetricks/winetricks"
> ```
> 
> If both fail, you will need to install either `curl` or `wget` on your system.
> 
> Let me know if that solves your problem.

That worked and got it to install fully. One thing I noticed was two of the errors were still there,
```
/home/litleck/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 44: return: can only `return' from a function or sourced script
ERROR: could not find game with APPID '489830'
/home/litleck/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 49: return: can only `return' from a function or sourced script
Installing script extender...
``` 
but it didn't stop it from installing and everything seems to work now.
Thanks.
