### ISSUE TITLE
Sort/Loot failed to run - Fallout 4

### ISSUE THREAD

**Issue by Lurkii-Desu** [rockerbacon/lutris-skyrimse-installers#165]
Sort plugins says Loot failed to run. 

Error I get is "Plugin 'Crossbow.esp' is in the load order file 'C:\users\steamuser\Local Settings\Application Data\ModOrganizer\Fallout4Linux\profiles\LinuxFO4\loadorder.txt' but does not exist on the filesystem in 'Z:\run\media\lurkii\Game SSD\SteamLibrary\steamapps\common\Fallout 4\Data'." This error applied to all plugins installed.

I'm guessing its not looking in the virtual file system and instead the game directory?
MO2 v2.2.2.1 and is installed in FO4's proton prefix. "Compatdata/377160/pfx/drive_c/Program files/"

**Comment by Lurkii-Desu** [comment]
I've tried the latest release on github instead of Lutris and the Sort option looks to have worked. Perhaps an issue with the current script on lutris.

**Comment by RadioactiveTurtle** [comment]
What do you mean by "The latest release on github"? Do you mean the script or lutris itself?

**Comment by Lurkii-Desu** [comment]
@RadioactiveTurtle The Script on Github, v2.8.6 was the one I used after trying the one directly from Lutris. MO2 wasn't working correctly after using the install script directly from Lutris.

**Comment by rockerbacon** [comment]
Script on Lutris.net is considerably old. I've sent the newer version to moderation.
