### ISSUE TITLE
vcredist-x86 sha256sum mismatch

### ISSUE THREAD

**Issue by silverhikari** [rockerbacon/lutris-skyrimse-installers#171]
when running the installer from the lutris website, i get a vcredist-x86 sha256sum mismatch which was fixed in the latest issue from winetricks (https://github.com/Winetricks/winetricks/issues/1642), i have ran the fixed version of winetricks(sha256sum:b32e46f689e28f1d4a368887458708eacd0422d4ddcb3d17b00741f742fce9d5) on a new wineprefix and it is able to download the new vcredist2019 and install it. but when i run the installer script it give the 256mismatch everytime even after clearing out the winetricks cache.

**Comment by rockerbacon** [comment]
See #61

**Comment by silverhikari** [comment]
i disagree with you has i had stated the winetricks i am using is the latest version available, and winetricks ran using the console on a new prefix can both download and install the vcredist-x86
