### ISSUE TITLE
command wine vc_redist.x86.exe /q returned status 231

### ISSUE THREAD

**Issue by BrightCrow** [rockerbacon/lutris-skyrimse-installers#174]
EDIT: Did not see there was the same subject already, sorry for the iteration, but I'm tired...

Hello,

Help please, I am getting mad with this installation...

I already tried the solutions presented in #61 but it still does not work.

I can copy the full terminal content of the installation of modorganizer2.yml if needed.

Here is the content of the terminal installation, the errors being:

`warning: Note: command wine vc_redist.x86.exe /q returned status 231. Aborting.`

and

```
Exit with returncode 256
2020-11-22 17:29:55,410: I can't move /home/bertrand/.cache/lutris/installer/mod-organizer-2/successful-prefix-preparation, it does not exist

**Comment by rockerbacon** [comment]
See #158
