### ISSUE TITLE
[FNV] VFS doesn't work

### ISSUE THREAD

**Issue by WannaCyp0r** [rockerbacon/lutris-skyrimse-installers#212]
Proton 5.0-10 on Debian 10
Explorer++ doesn't show mod files and none of the mods installed with mo2 were loaded in game.
[lutris-mo2-fnv.log](https://github.com/rockerbacon/lutris-skyrimse-installers/files/6175424/lutris-mo2-fnv.log)

**Comment by SleepyFugu** [comment]
Might want to take a look at this issue:
https://github.com/Modorganizer2/modorganizer/issues/372

**Comment by WannaCyp0r** [comment]
Solved, VFS doesn't work for symlink folder.
Closing.
