### ISSUE TITLE
Install doesn't seem to work, not sure what if I'm missing something or what

### ISSUE THREAD

**Issue by dylanfurr** [rockerbacon/lutris-skyrimse-installers#230]
As you can probably tell, I'm pretty new to Linux, and recently I've tried to get MO2 to work with it, though with great difficulty. No matter what i do, I keep getting the same log: 

ERROR: could not find game with APPID '489830'
/home/dylan/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 49: return: can only `return' from a function or sourced script
Installing script extender...
Executing mkdir -p /home/dylan/.local/share/Steam/steamapps/compatdata/489830
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 40
drwxrwxr-x 10 dylan dylan 4096 Jul  3 15:25 .
drwxrwxr-x  4 dylan dylan 4096 Jul  3 22:55 ..
drwx------  4 dylan dylan 4096 Jul  3 22:55 java
drwxrwxr-x  2 dylan dylan 4096 Jul  3 15:23 openxr
drwxrwxr-x  4 dylan dylan 4096 Jul  3 15:22 ProgramData
drwxrwxr-x  6 dylan dylan 4096 Jul  3 15:22 Program Files
drwxrwxr-x  7 dylan dylan 4096 Jul  3 15:22 Program Files (x86)
drwxrwxr-x  4 dylan dylan 4096 Jul  3 15:22 users
drwxrwxr-x  3 dylan dylan 4096 Jul  3 15:22 vrclient
drwxrwxr-x 19 dylan dylan 4096 Jul  3 22:55 windows

Registry info:
/home/dylan/.local/share/Steam/steamapps/compatdata/489830/pfx/system.reg:#arch=win64
/home/dylan/.local/share/Steam/steamapps/compatdata/489830/pfx/user.reg:#arch=win64
/home/dylan/.local/share/Steam/steamapps/compatdata/489830/pfx/userdef.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message "wine: Call from 0x7b02dae6 to unimplemented function shell32.dll.SHGetFolderPathW, aborting
wine: Unimplemented function shell32.dll.SHGetFolderPathW called at address 000000007B02DAE6 (thread 000b), starting debugger..." 

Game in question is Skyrim SE. I'm on running Proton 5.0, Lutris version 0.5.8.3, and and for Wine, I'm on Lutris-5.7-11. Not sure if maybe I'm using an older/newer version for one of these, or maybe I've done something wrong. Any help would be appreciated!

**Comment by dylanfurr** [comment]
UPDATE; Looks to be fixed now, though I am curious about if it's possible to get onto the latest SKSE64 build.

**Comment by ivakam** [comment]
Was there anything you did to fix this? I'm getting the same issue on manjaro. The installer logs "found game" but then later throws an error that the game could not be found.
