### ISSUE TITLE
Could not find 'Skyrim' in your Steam library

### ISSUE THREAD

**Issue by Muxed0** [rockerbacon/lutris-skyrimse-installers#242]
I was trying to install MO2 for skyrim but this error quickly popped up. I had no trouble setting up vortex for another game so I'm a bit confused.

I own skyrim LE and SE (but LE seems to have more positive reports here so I went with this). I downloaded the game and started it up with steam proton to set window size and as part of the instructions, but then the installation failed like this. I was using the most recent version of proton at first and then tried 5.0, but 5.0 doesn't even launch the game (fatal renderer error).

I'm on POP!_OS 20.04 and have installed the game (and set the mo2 install location besides it) on a secondary hard drive mounted in root. I imagine this is the cause of the problem but I don't see a way to input a custom install location. Is there any way I can make it work still?

**Comment by Muxed0** [comment]
Small update: the script searches an install directory that is not even listed in my steam library because the only thing installed there is steam VR. Even installing Skyrim in the base game library directory does not work.

**Comment by milliams** [comment]
I *think* that this is the same issue as #241. I've posted what I did to fix it there so maybe that will help?

**Comment by Muxed0** [comment]
I don't think so because in #241 the script does find the game, in my case it doesn't.
`if [ "$?" != "0" ]; then
    "/home/jean/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Error while installing winetricks, please run Lutris from a terminal and check the logs"
    exit 1
fi

# workaround to stop installation if command fails
echo "success" > '/home/jean/.cache/lutris/installer/mod-organizer-2/successful-prefix-preparation'
Initial process has started with pid 7464
Start monitoring process.
Searching for Steam in '/home/jean/.steam/debian-installation'
Found Steam
Searching for Steam in '/home/jean/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Found Steam
Searching for game in library '/home/jean/.var/app/com.valvesoftware.Steam/.local/share/Steam'
ERROR: could not find game with APPID '72850'
/home/jean/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 49: return: can only `return' from a function or sourced script`

**Comment by Muxed0** [comment]
Small update: I was able to get it installed by going in the .sh file as said in #241 and _adding_ rather than removing an installation directory. Only problem now is that the game won't launch under proton 5.0, spitting out a `Failed to initialize renderer, Unknown error creating the renderer` error. I naively tried to modify the laun.sh and download.sh file to use proton 6.3 instead but as expected mo2 complained by not running anymore.

**Comment by Slippingstones** [comment]
If anyone else is having this issue re-install Skyrim in a new steamlibrary folder by going to your Steam settings> downloads> steam library folders > + button
 I couldn't get this to work for the life of me until I did this. If skyrim is installed in a hidden folder like .skyrim in say Fedora IT WILL NOT FIND YOUR GAME.

**Comment by SFMason** [comment]
> Edit2: This only occurs when going in windowed mode, but 6.3 allows windowed and full-screen mode. I guess this issue can be closed now, but does anyone know why only Proton 5.0 work? What would it take to make 6.3 work as well?

This may not be strictly relevant to the original issue, but switching to fullscreen definitely fixes the "Failed to initialize renderer" crash. I'd also like to add that any mod that adds windowed fullscreen mode, [such as this one](https://www.nexusmods.com/skyrim/mods/40706), will cause the "failed to initialize renderer" crash. Hopefully this will help anyone googling around for this issue, since it's a subtle way to run into this issue.
