### ISSUE TITLE
Detection of Fallout NV

### ISSUE THREAD

**Issue by leylaso** [rockerbacon/lutris-skyrimse-installers#262]
Install script in lutris crashes with the following error:

Could not find 'Fallout New Vegas enplczru' in your Steam library

Investigating further, I note that the app id for my Fallout New Vegas is 22380, and the script spits out an error that it cannot find 22490.

Tried simlinking the directory in compatdata to no avail.

```
/home/leyla/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 49: return: can only `return' from a function or sourced script
Searching for Steam in '/home/leyla/.steam'
Found Steam
Searching for Steam in '/home/leyla/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Steam not found in this install path
Searching for game in library '/home/leyla/.steam/steam'
Found game
/home/leyla/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 44: return: can only `return' from a function or sourced script
Searching for game in library '/home/leyla/.steam/steam'
Found game
/home/leyla/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 44: return: can only `return' from a function or sourced script
ERROR: could not find game with APPID '22490'
/home/leyla/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 49: return: can only `return' from a function or sourced script
```

**Comment by leylaso** [comment]
I think the issue must lie in the logic of gamesinfo/newvegas.sh

**Comment by leylaso** [comment]
And I was wrong eveidently as hardcoding the game id in gamesinfo/newvegas.sh did nothing to resolve the problem

**Comment by leylaso** [comment]
So. I bypassed this error by changing all the return statements to exit statements in find-library-for-appid.sh. Because return doesn't seem to get along with my sh. Hope this is of help in resolving this error.

**Comment by EIRNf** [comment]
Came across the same issue. Changing all the return statements to exit statements definitely seems to fix it. Thank you for finding that out!

To avoid fully running the shell scripts locally you can modify the installer modorganizer2.yml file that lutris runs to point to the newer versions of the utils scripts(2.9.0). As it seems that the issue has been noticed and prepared for a future release.

Replace lines 11-13 of the modorganizer2.yml with the following:

# utils
 - dialog: https://github.com/rockerbacon/lutris-skyrimse-installers/releases/download/2.9.0-utils/dialog.sh
 - find_library_for_appid: https://github.com/rockerbacon/lutris-skyrimse-installers/releases/download/2.9.0-utils/find-library-for-appid.sh

**Comment by juliovco** [comment]
I was having the same issue with Skyrim SE, and pointing to the newer utils scripts solved it, thank you.
