### ISSUE TITLE
Loot might need wineHQ staging

### ISSUE THREAD

**Issue by tetoNidan** [rockerbacon/lutris-skyrimse-installers#3]
Opening new issue as requested. Cant find loot version as requested. Dont know where to look. I tried in Vortex -> about, but couldn't find it in there. Tried wineconfig to but it's not under applications. Cant remember the command to open a CMD terminal and I don't know much about getting .exe's version info that way. 

Are you talking about Vortex versions? Vortex version is 0.17.11.

**Comment by rockerbacon** [comment]
The LOOT version should be found inside LOOT, not inside Vortex. Open LOOT, click on the tree dots in the upper right corner, click on "About".

**Comment by rockerbacon** [comment]
Wine updated to version 4.12.1 in release 1.8
