### ISSUE TITLE
Fallout 4 Install fails in 2.3.x

### ISSUE THREAD

**Issue by ajventer** [rockerbacon/lutris-skyrimse-installers#31]
It seems the install for Fallout 4 is broken in the current versions.

After several tries, I ran lutris in debug mode and captured all output, hope it helps.

[fallout4.log](https://github.com/rockerbacon/lutris-skyrimse-installers/files/4608752/fallout4.log)

**Comment by ajventer** [comment]
Found the issue: typo on line 55 of the script. Nexus Game ID is written as Fallou4 instead of Fallout4.

**Comment by ajventer** [comment]
This fix is missing in 2.6.0 - is that just because it's still in the unstable line ? Or was it meant ot be in stable by now ?

**Comment by rockerbacon** [comment]
Something when solving a merge conflict, I'll get it fixed
