### ISSUE TITLE
FNIS fails on external HD

### ISSUE THREAD

**Issue by tetoNidan** [rockerbacon/lutris-skyrimse-installers#4]
There is no way to use FNIS as Administrator. Wines default permissions are Admin privilege so you cant elevate permissions to admin as far as I know. Never run wine apps as root (sudo)! Installing on external HD might be a bust if you want to use FNIS and possibly bodySlide. I know the setting you were referring to, it's in the body slide setup, under "start in" option. No change will work. Tried every fix I can think of. Everything will work great if vortex is installed on the same HD as your os running wine runtime. I had Skyrim bodyslide working and FNIS many times before.

**Comment by tetoNidan** [comment]
Installing Vortex to main OS HD and updating where Vortex places its mods staging folder and download folder in Vortex settings will get everything but FNIS working. No need to install Vortex prefix to same HD as game install HD. Body slide will work. FNIS still has same error. Im gonna nuke your vortex and install the other to test and verify that the other Vortex from Lutris does not have the same problem; as I have had everything working before.

Also I did an update of Vortex because Im about to nuke it and thought Id test updating and everything still works. Mods are deploying. No crash, still have access to saved games. Not sure that it broke anything.

Wine can be very buggy and everyone mileage may very. Thought I'd ask because some settings seem to be left undeleted like Vortex will always find my skyrim install and be Descovered no matter who's version of vortex I download. and FNIS will always have body arm fix checked on brand new install. It's like maybe there is a registry file that never gets deleted when I delete the Vortex prefix.

**Comment by rockerbacon** [comment]
As much as I'd love to ensure every single external tool works flawlessly the scope of the project is limited to ensuring Vortex, SSE and SKSE64 work.

I'll leave the issue open in case anyone wants to pick it up, but I will not work on it.

**Comment by tetoNidan** [comment]
Actually close it. Its not possible to elevate to admin as you already are as wineuser from what i have read. You need to be on the same drive. Nuked it and bought a bigger SSD. Still cant get fallout 4 to be found. All symbolic links are there. Kind of abandoned fo4 for now. Mods from NMM wont direct download but everything else works for skyrim at least.
