### ISSUE TITLE
cannot install MO2.

### ISSUE THREAD

**Issue by tetoNidan** [rockerbacon/lutris-skyrimse-installers#44]
lutris -i ~/Desktop/modorganizer2.yml 
2020-05-12 09:04:33,576: Running Lutris 0.5.6
2020-05-12 09:04:33,577: Using NVIDIA drivers 440.82 for x86_64
2020-05-12 09:04:33,577: GPU: GeForce GTX 1070
2020-05-12 09:04:33,577: GPU: 10DE:1BE1 1043:1660 using nvidia drivers
2020-05-12 09:04:33,595: Vulkan is supported
2020-05-12 09:04:33,596: Updating DXVK versions
2020-05-12 09:04:33,730: Connected to lutris.net as tldr
2020-05-12 09:04:39,212: Downloading file 1 of 16
2020-05-12 09:04:39,214: File mod-organizer-2/dialog already cached
2020-05-12 09:04:39,215: Downloading file 2 of 16
2020-05-12 09:04:39,216: File mod-organizer-2/find_library_for_appid already cached
2020-05-12 09:04:39,217: Downloading file 3 of 16
2020-05-12 09:04:39,218: File mod-organizer-2/gamesinfo already cached
2020-05-12 09:04:39,218: Downloading file 4 of 16
2020-05-12 09:04:39,219: File mod-organizer-2/proton_launcher already cached
2020-05-12 09:04:39,220: Downloading file 5 of 16
2020-05-12 09:04:39,221: File mod-organizer-2/wine_launcher already cached
2020-05-12 09:04:39,221: Downloading file 6 of 16
2020-05-12 09:04:39,222: File mod-organizer-2/nxm_broker already cached
2020-05-12 09:04:39,223: Downloading file 7 of 16
2020-05-12 09:04:39,224: File mod-organizer-2/nxm_mime_handler already cached
2020-05-12 09:04:39,224: Downloading file 8 of 16
2020-05-12 09:04:39,225: File mod-organizer-2/openjdk already cached
2020-05-12 09:04:39,226: Downloading file 9 of 16
2020-05-12 09:04:39,227: File mod-organizer-2/fose already cached
2020-05-12 09:04:39,227: Downloading file 10 of 16
2020-05-12 09:04:39,228: File mod-organizer-2/f4se already cached
2020-05-12 09:04:39,229: Downloading file 11 of 16
2020-05-12 09:04:39,230: File mod-organizer-2/nvse already cached
2020-05-12 09:04:39,230: Downloading file 12 of 16
2020-05-12 09:04:39,231: File mod-organizer-2/mwse already cached
2020-05-12 09:04:39,231: Downloading file 13 of 16
2020-05-12 09:04:39,232: File mod-organizer-2/obse already cached
2020-05-12 09:04:39,233: Downloading file 14 of 16
2020-05-12 09:04:39,234: File mod-organizer-2/skse already cached
2020-05-12 09:04:39,234: Downloading file 15 of 16
2020-05-12 09:04:39,235: File mod-organizer-2/skse64 already cached
2020-05-12 09:04:39,235: Downloading file 16 of 16
2020-05-12 09:04:39,236: File mod-organizer-2/mo_archive already cached

(lutris:3741): Gtk-CRITICAL **: 09:04:46.605: gtk_tree_model_get_column_type: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed

(lutris:3741): Gtk-CRITICAL **: 09:04:46.605: gtk_combo_box_get_active_id: assertion 'gtk_tree_model_get_column_type (model, column) == G_TYPE_STRING' failed
Running /bin/bash -c xdg-mime default modorganizer2-nxm-handler.desktop x-scheme-handler/nxm
Initial process has started with pid 3814
Game is considered started.
Game is considered exited.
Initial process has exited.
All children have exited.
Exit with returncode 0

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 37319384 bytes (36 MiB)                                     

Extracting archive: /home/took/Downloads/LutrisCache/mod-organizer-2/openjdk/OpenJDK8U-jre_x64_windows_8u252b09.zip
--
Path = /home/took/Downloads/LutrisCache/mod-organizer-2/openjdk/OpenJDK8U-jre_x64_windows_8u252b09.zip
Type = zip
Physical Size = 37319384

Everything is Ok                                      

Folders: 15
Files: 121
Size:       94859720
Compressed: 37319384

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 384875 bytes (376 KiB)                                   

Extracting archive: /home/took/Downloads/LutrisCache/mod-organizer-2/fose/fose_v1_2_beta2.7z
--
Path = /home/took/Downloads/LutrisCache/mod-organizer-2/fose/fose_v1_2_beta2.7z
Type = 7z
Physical Size = 384875
Headers Size = 3155
Method = LZMA:6m BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 8
Files: 184
Size:       4753751
Compressed: 384875

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 598435 bytes (585 KiB)                                   

Extracting archive: /home/took/Downloads/LutrisCache/mod-organizer-2/f4se/f4se_0_06_21.7z
--
Path = /home/took/Downloads/LutrisCache/mod-organizer-2/f4se/f4se_0_06_21.7z
Type = 7z
Physical Size = 598435
Headers Size = 5414
Method = LZMA2:22 LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 14
Files: 393
Size:       3284040
Compressed: 598435

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 712979 bytes (697 KiB)                                   

Extracting archive: /home/took/Downloads/LutrisCache/mod-organizer-2/nvse/nvse_5_1_beta4.7z
--
Path = /home/took/Downloads/LutrisCache/mod-organizer-2/nvse/nvse_5_1_beta4.7z
Type = 7z
Physical Size = 712979
Headers Size = 4131
Method = LZMA2:6m LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 12
Files: 231
Size:       4902927
Compressed: 712979

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 4095963 bytes (4000 KiB)                                 

Extracting archive: /home/took/Downloads/LutrisCache/mod-organizer-2/mwse/mwse.zip
--
Path = /home/took/Downloads/LutrisCache/mod-organizer-2/mwse/mwse.zip
Type = zip
Physical Size = 4095963

Everything is Ok

Folders: 23
Files: 127
Size:       14201986
Compressed: 4095963

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 1662426 bytes (1624 KiB)                                 

Extracting archive: /home/took/Downloads/LutrisCache/mod-organizer-2/obse/obse_0021.zip
--
Path = /home/took/Downloads/LutrisCache/mod-organizer-2/obse/obse_0021.zip
Type = zip
Physical Size = 1662426
Comment = ; WinRAR
; Multifunctional Integrated Archive Manager

Everything is Ok

Folders: 12
Files: 342
Size:       6092629
Compressed: 1662426
Running /bin/bash -c printf '\x90\x90\x90' | dd conv=notrunc of='/home/took/.cache/lutris/installer/mod-organizer-2/oblivion-script-extender/obse_loader.exe' bs=1 seek=$((0x14cb))
Initial process has started with pid 3871
Game is considered started.
3+0 records in
3+0 records out
3 bytes copied, 2.9839e-05 s, 101 kB/s
Game is considered exited.
Initial process has exited.
All children have exited.
Exit with returncode 0

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 624845 bytes (611 KiB)                                   

Extracting archive: /home/took/Downloads/LutrisCache/mod-organizer-2/skse/skse_1_07_03.7z
--
Path = /home/took/Downloads/LutrisCache/mod-organizer-2/skse/skse_1_07_03.7z
Type = 7z
Physical Size = 624845
Headers Size = 8072
Method = LZMA2:22 LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 14
Files: 544
Size:       3591799
Compressed: 624845

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 755625 bytes (738 KiB)                                     

Extracting archive: /home/took/Downloads/LutrisCache/mod-organizer-2/skse64/skse64_2_00_17.7z
--
Path = /home/took/Downloads/LutrisCache/mod-organizer-2/skse64/skse64_2_00_17.7z
Type = 7z
Physical Size = 755625
Headers Size = 7057
Method = LZMA2:6m LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 13
Files: 520
Size:       4426059
Compressed: 755625
Running /bin/bash -c nexus_game_id=fallout4
runner=proton

if [ ! -f "/home/took/.cache/lutris/installer/mod-organizer-2/gamesinfo/$nexus_game_id.sh" ]; then
    "/home/took/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Could not find gameinfo for '$nexus_game_id', remove Lutris cache and try again"
    exit 1
fi

source "/home/took/.cache/lutris/installer/mod-organizer-2/gamesinfo/$nexus_game_id.sh"

if [ -z "$game_appid" ]; then
    echo "ERROR: empty game_appid" >&2
    exit 1
elif [ -z "$game_steam_subdirectory" ]; then
    echo "ERROR: empty steam_subdirectory" >&2
    exit 1
fi

shared="/home/took/.local/share/modorganizer2"

case "$runner" in
    proton)
        mo2_tricks="vcrun2019"
        mo2_options=""

        steam_library=$("/home/took/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh" $game_appid)

        if [ ! -d "$steam_library" ]; then
            "/home/took/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
                "Could not find '$game_steam_subdirectory' in your Steam library"
            exit 1
        fi

        game_prefix="$steam_library/steamapps/compatdata/$game_appid/pfx"
        game_installation="$steam_library/steamapps/common/$game_steam_subdirectory"
        game_tricks="$game_protontricks"

        echo -e \
        "#!/bin/bash\n\n'$shared/proton-launcher.sh' $mo2_options $game_proton_options \"\$@\" $game_appid '/home/took/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe'" \
        > "/home/took/Games/mod-organizer-2/run.sh"

        echo -e \
        "#!/bin/bash\n\n'$shared/proton-launcher.sh' $mo2_options $game_proton_options \"\$@\" $game_appid '/home/took/Games/mod-organizer-2/ModOrganizer2/nxmhandler.exe' \"\$1\"" \
        > "/home/took/Games/mod-organizer-2/download.sh"
        ;;

    wine)
        mo2_tricks="vcrun2019 dotnet40"
        mo2_options="--proton-wine --winever 5.*"

        "/home/took/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" warnbox \
            "As of version 5.7, Wine still does not fully support Mod Organizer 2.2.1 and later.\nFor this reason this installer uses the Wine version bundled with Proton 5.0.\nMake sure you have Steam and Proton 5.0 installed on your system"

        game_prefix=$( \
            "/home/took/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" directorypicker \
                "Inform the path to your wineprefix" \
        )
        if [ -z "$game_prefix" ]; then
            echo "ERROR: Installation canceled by user" >&2
            exit 1
        fi

        game_tricks="$game_winetricks"

        install_path_candidates=( \
            "$game_prefix/drive_c/Program Files (x86)/Steam/steamapps/common/$game_steam_subdirectory" \
            "$game_prefix/drive_c/GOG Games/$game_steam_subdirectory" \
        )
        if [ -n "$game_gog_subdirectory" ]; then
            install_path_candidates+=( \
                "$game_prefix/drive_c/GOG Games/$game_gog_subdirectory" \
            )
        fi
        if [ "$nexus_game_id" == "fallout3" ]; then
            install_path_candidates+=( \
                "$game_prefix/drive_c/Program Files (x86)/Steam/steamapps/common/Fallout 3" \
                "$game_prefix/drive_c/GOG Games/Fallout 3" \
            )
        fi

        for path in "${install_path_candidates[@]}"; do
            echo "Searching for game at '$path'"
            if [ -d "$path" ]; then
                echo "Found game"
                game_installation="$path"
                break
            fi
        done

        if [ -z "$game_installation" ]; then
            game_installation=$( \
                "/home/took/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" directorypicker \
                    "Could not automatically find the game.\nPlease inform the path where the game is installed" \
            )
            if [ -z "$game_installation" ]; then
                echo "ERROR: installation canceled by user" >&2
                exit 1
            fi
        fi

        # TODO: uncomment once Wine fixes issues with VC2019
        # winever=$( \
        #     "/home/took/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" textentry \
        #         "Inform which version of Wine you're using\nLeave as * to use the latest version available on Lutris" \
        #         "*" \
        # )
        # if [ -z "$winever" ]; then
        #     echo "ERROR: Installation canceled by user" >&2
        #     exit 1
        # fi

        echo -e \
        "#!/bin/bash\n\nWINEPREFIX='$game_prefix' '$shared/wine-launcher.sh' $mo2_options $game_wine_options \"\$@\" '/home/took/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe'" \
        > "/home/took/Games/mod-organizer-2/run.sh"

        echo -e \
        "#!/bin/bash\n\nWINEPREFIX='$game_prefix' '$shared/wine-launcher.sh' $mo2_options $game_wine_options \"\$@\" '/home/took/Games/mod-organizer-2/ModOrganizer2/nxmhandler.exe'" \
        > "/home/took/Games/mod-organizer-2/download.sh"
        ;;
esac

if [ -d "/home/took/.cache/lutris/installer/mod-organizer-2/${nexus_game_id}-script-extender" ]; then
    echo "Installing script extender..."

    output=$( \
        cp -af \
        "/home/took/.cache/lutris/installer/mod-organizer-2/${nexus_game_id}-script-extender/." \
        "$game_installation/" 2>&1 \
    )
    if [ "$?" != "0" ]; then
        "/home/took/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
            "Error while installing script extender: $output"
        exit 1
    fi
fi

mkdir -p "$game_prefix/drive_c/java"
output=$( \
    cp -af \
    "/home/took/.cache/lutris/installer/mod-organizer-2/extracted-openjdk/." \
    "$game_prefix/drive_c/java/" 2>&1 \
)
if [ "$?" != "0" ]; then
    "/home/took/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Error while installing OpenJDK: $output"
    exit 1
fi

WINEPREFIX="$game_prefix" \
"/home/took/.local/share/lutris/runtime/winetricks/winetricks" -q $mo2_tricks $game_tricks
if [ "$?" != "0" ]; then
    "/home/took/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Error while installing winetricks, please run Lutris from a terminal and check the logs"
    exit 1
fi

# workaround to stop installation if command fails
echo "success" > '/home/took/.cache/lutris/installer/mod-organizer-2/successful-prefix-preparation'
Initial process has started with pid 3896
Game is considered started.
Searching for game in library '/home/took/.steam/steam'
Found game
Installing script extender...
------------------------------------------------------
wineserver not found!
------------------------------------------------------
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Gtk-Message: 09:04:56.295: GtkDialog mapped without a transient parent. This is discouraged.
Game is considered exited.
Initial process has exited.
All children have exited.
Exit with returncode 256
2020-05-12 09:05:00,066: I can't move /home/took/.cache/lutris/installer/mod-organizer-2/successful-prefix-preparation, it does not exist
None
2020-05-12 09:05:00,066: Error while completing task <bound method CommandsMixin.move of <lutris.installer.interpreter.ScriptInterpreter object at 0x7fe7a994dfd0>>: I can't move /home/took/.cache/lutris/installer/mod-organizer-2/successful-prefix-preparation, it does not exist
None
<class 'lutris.installer.errors.ScriptingError'> I can't move /home/took/.cache/lutris/installer/mod-organizer-2/successful-prefix-preparation, it does not exist
None
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 286, in move
    raise ScriptingError("I can't move %s, it does not exist" % src)
Gtk-Message: 09:05:00.735: GtkDialog mapped without a transient parent. This is discouraged.
2020-05-12 09:05:02,892: Cancelling installation of Mod Organizer 2
2020-05-12 09:05:04,664: Shutting down Lutris

**Comment by rockerbacon** [comment]
Looks like a problem with Winetricks dependencies. Have you followed Lutris' guide on installing Wine-Staging?

**Comment by tetoNidan** [comment]
Yeah, about a year ago.

**Comment by tetoNidan** [comment]
After reinstallation of lutris; MO2 is a go. Thanks rockerbacon man. Im gonna mod out some fallout.
