### ISSUE TITLE
Pure wine - broken within lutris

### ISSUE THREAD

**Issue by ajventer** [rockerbacon/lutris-skyrimse-installers#49]
Pure Wine setups cannot launch from within lutris, but work fine if calling run.sh manually.

Error from within Lutris:

	LD_LIBRARY_PATH='/home/metalpoetza/.steam/steam/steamapps/common/Proton 5.0/lib64:/home/metalpoetza/.steam/steam/steamapps/common/Proton 5.0/lib:/games/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/games/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/libfakeroot:/usr/lib32:/usr/lib/libupnp-1.8:/usr/lib/openmpi:/usr/lib:/games/Steam/ubuntu12_32/steam-runtime/i386/lib/i368-linux-gnu:/games/Steam/ubuntu12_32/steam-runtime/i386/lib:/games/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/games/Steam/ubuntu12_32/steam-runtime/i386/usr/lib:/games/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/games/Steam/ubuntu12_32/steam-runtime/amd64/lib:/games/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/games/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib' \
	 \
	WINEPREFIX='/games/FNV'
	\
	'/home/metalpoetza/.steam/steam/steamapps/common/Proton 5.0/dist/bin/wine' '/games/mo2fnv/ModOrganizer2/ModOrganizer.exe' 

wineserver: using server-side synchronization.
wine client error:0: version mismatch 621/597.
Your wine binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?
Game is considered exited.
Initial process has exited.
All children have exited.
Exit with returncode 256
DEBUG    2020-05-14 10:44:55,139 [command.on_stop:182]:The process has terminated with code 0
DEBUG    2020-05-14 10:44:55,140 [command.stop:266]:Management process looks dead already.
DEBUG    2020-05-14 10:44:55,140 [command.stop:278]:logger already detached
DEBUG    2020-05-14 10:44:56,887 [game.beat:596]:Game thread stopped
WARNING  2020-05-14 10:44:56,887 [game.on_game_quit:626]:Game still running (state: running)
INFO     2020-05-14 10:44:56,887 [game.stop:611]:Stopping MO2FNV (linux)
DEBUG    2020-05-14 10:44:56,887 [command.stop:266]:Management process looks dead already.
DEBUG    2020-05-14 10:44:56,887 [command.stop:278]:logger already detached
DEBUG    2020-05-14 10:44:56,892 [game.on_game_quit:645]:MO2FNV stopped at Thu, 14 May 2020 10:44:56
DEBUG    2020-05-14 10:44:56,892 [game.save:249]:Saving MO2FNV (linux)
DEBUG    2020-05-14 10:44:56,935 [lutriswindow.on_game_updated:779]:Updating game MO2FNV (linux)
INFO     2020-05-14 10:45:01,129 [application.do_shutdown:491]:Shutting down Lutris

**Comment by rockerbacon** [comment]
Looks like an old wineserver processes kept it from running. That wineserver process might have been terminated at some point before you executed `run.sh` manually.

If you are still having the issue, show the me the contents of `run.sh` and tell me if you are using any arguments in Lutris.

**Comment by ajventer** [comment]
That is what I normally ascribe to that error - but it seems to only happen in Lutris, and it keeps happening. Even after a successful usage from run.sh, if you start lutris and try it from there, it fails once again.

[metalpoetza@aj-pc mo2fnv]$ cat run.sh
#!/bin/bash

WINEPREFIX='/games/FNV' '/home/metalpoetza/.local/share/modorganizer2/wine-launcher.sh' --proton-wine --winever 5.*  "$@" '/games/mo2fnv/ModOrganizer2/ModOrganizer.exe'

-----
I have no arguments set for FNV in lutris.

Full lutris logs below:
---
[metalpoetza@aj-pc mo2fnv]$ lutris -d
INFO     2020-05-14 17:47:58,060 [application.do_command_line:245]:Running Lutris 0.5.6
INFO     2020-05-14 17:47:58,075 [startup.check_driver:54]:Using NVIDIA drivers 440.82 for x86_64
INFO     2020-05-14 17:47:58,075 [startup.check_driver:60]:GPU: GeForce GTX 1050 Ti
INFO     2020-05-14 17:47:58,075 [startup.check_driver:77]:GPU: 10DE:1C82 10DE:11BF using nvidia drivers
INFO     2020-05-14 17:47:58,223 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-05-14 17:47:58,240 [dxvk.get_dxvk_versions:22]:Updating DXVK versions
DEBUG    2020-05-14 17:47:58,825 [http.get:65]:GET https://lutris.net/api/runtime
DEBUG    2020-05-14 17:47:58,830 [store.get_missing_media:212]:Requesting missing icons from API for mod-organizer-2
DEBUG    2020-05-14 17:47:58,830 [http.get:65]:GET https://lutris.net/api/games
INFO     2020-05-14 17:47:58,841 [lutriswindow.toggle_connection:642]:Connected to lutris.net as metalpoetza
DEBUG    2020-05-14 17:47:58,841 [http.get:65]:GET https://lutris.net/api/games/library/metalpoetza
DEBUG    2020-05-14 17:47:59,542 [api.get_game_api_page:132]:Loaded 1 games from page 1
DEBUG    2020-05-14 17:48:03,301 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2020-05-14 17:48:03,365 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2020-05-14 17:48:03,423 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2020-05-14 17:48:21,367 [application.launch:379]:Launching MO2FNV (linux) (139858188532928)
DEBUG    2020-05-14 17:48:21,389 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2020-05-14 17:48:21,449 [game.configure_game:334]:Launching MO2FNV: {'command': ['/games/mo2fnv/run.sh']}
DEBUG    2020-05-14 17:48:21,449 [game.configure_game:335]:Game info: {
  "command": [
    "/games/mo2fnv/run.sh"
  ]
}
DEBUG    2020-05-14 17:48:21,453 [command.start:133]:Running /usr/share/lutris/bin/lutris-wrapper MO2FNV 0 0 /games/mo2fnv/run.sh
DEBUG    2020-05-14 17:48:21,453 [command.start:135]:ENV: SDL_VIDEO_FULLSCREEN_DISPLAY="off"
DEBUG    2020-05-14 17:48:21,453 [command.start:135]:ENV: STEAM_RUNTIME="/home/metalpoetza/.local/share/lutris/runtime/steam"
DEBUG    2020-05-14 17:48:21,453 [command.start:135]:ENV: LD_LIBRARY_PATH="/usr/lib/libfakeroot:/usr/lib/libupnp-1.8:/usr/lib/openmpi:/usr/lib32:/usr/lib:/usr/lib64:/home/metalpoetza/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/metalpoetza/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/metalpoetza/.local/share/lutris/runtime/steam/i386/lib:/home/metalpoetza/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/metalpoetza/.local/share/lutris/runtime/steam/i386/usr/lib:/home/metalpoetza/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/metalpoetza/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/metalpoetza/.local/share/lutris/runtime/steam/amd64/lib:/home/metalpoetza/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/metalpoetza/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH"
DEBUG    2020-05-14 17:48:21,453 [command.start:135]:ENV: game_name="MO2FNV"
DEBUG    2020-05-14 17:48:21,453 [command.start:135]:ENV: PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/lib/python3.8/site-packages"
lutris-wrapper: MO2FNV
Running /games/mo2fnv/run.sh
Initial process has started with pid 604720
Game is considered started.


	LD_LIBRARY_PATH='/home/metalpoetza/.steam/steam/steamapps/common/Proton 5.0/lib64:/home/metalpoetza/.steam/steam/steamapps/common/Proton 5.0/lib:/games/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/games/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/libfakeroot:/usr/lib32:/usr/lib/libupnp-1.8:/usr/lib/openmpi:/usr/lib:/games/Steam/ubuntu12_32/steam-runtime/i386/lib/i368-linux-gnu:/games/Steam/ubuntu12_32/steam-runtime/i386/lib:/games/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/games/Steam/ubuntu12_32/steam-runtime/i386/usr/lib:/games/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/games/Steam/ubuntu12_32/steam-runtime/amd64/lib:/games/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/games/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib' \
	 \
	WINEPREFIX='/games/FNV'
	\
	'/home/metalpoetza/.steam/steam/steamapps/common/Proton 5.0/dist/bin/wine' '/games/mo2fnv/ModOrganizer2/ModOrganizer.exe' 


wineserver: using server-side synchronization.
wine client error:0: version mismatch 621/597.
Your wine binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?
Game is considered exited.
Initial process has exited.
All children have exited.
Exit with returncode 256
DEBUG    2020-05-14 17:48:21,887 [command.on_stop:182]:The process has terminated with code 0
DEBUG    2020-05-14 17:48:21,889 [command.stop:266]:Management process looks dead already.
DEBUG    2020-05-14 17:48:21,889 [command.stop:278]:logger already detached
DEBUG    2020-05-14 17:48:23,483 [game.beat:596]:Game thread stopped
WARNING  2020-05-14 17:48:23,483 [game.on_game_quit:626]:Game still running (state: running)
INFO     2020-05-14 17:48:23,484 [game.stop:611]:Stopping MO2FNV (linux)
DEBUG    2020-05-14 17:48:23,485 [command.stop:266]:Management process looks dead already.
DEBUG    2020-05-14 17:48:23,485 [command.stop:278]:logger already detached
DEBUG    2020-05-14 17:48:23,510 [game.on_game_quit:645]:MO2FNV stopped at Thu, 14 May 2020 17:48:23
DEBUG    2020-05-14 17:48:23,510 [game.save:249]:Saving MO2FNV (linux)
DEBUG    2020-05-14 17:48:23,583 [lutriswindow.on_game_updated:779]:Updating game MO2FNV (linux)

**Comment by rockerbacon** [comment]
This one actually puzzled me quite a lot for a moment.

The probable cause is the lutris-wrapper, it is adding a bunch of unnecessary envs to the application which it should not. There's a very dangerous one in particular: LD_LIBRARY_PATH is a hack and should not be used without perfect knowledge of what libraries an application uses.

Right click the game and go to `Configure > System Options` check the option `Disable Lutris Runtime`. See if that works.

Working or not it's something I must implement into the installer as it can cause tons of problems.

**Comment by ajventer** [comment]
LUTRIS runtime is, indeed, the cause of the problem - the moment I turned it off my pure-wine MO2 for FNV launched cleanly from within lutris.
