### ISSUE TITLE
FNIS Error 2012

### ISSUE THREAD

**Issue by klapperking** [rockerbacon/lutris-skyrimse-installers#57]
Heya (me again)!

I've been setting up for a couple of days now and it works like a charm, thank you for this!

The only thing I haven't been able to get working is FNIS.

When I update FNIS Behaviour I get the Error 2012 (as seen in the Screenshot)

![Screenshot from 2020-05-16 23-43-24](https://user-images.githubusercontent.com/64156820/82130815-213ea700-97cf-11ea-936a-594d61d738e6.png)

As I am certain that I have set everything up correctly, I am wondering whether it might be related to being on Linux in general.

However, if this is a known issue or somebody knows of a possible solution, that would be great!

If you, @rockerbacon, don't think this is related to this page, feel free to close this issue without comment.

Cheers!

**Comment by rockerbacon** [comment]
Ran into the same problem, but it apparently isn't Linux. I'd link to the solution Forum, but it's on LovesLab.

You need to install just the FNIS executable into Skyrim's data folder, following the same directory structure it in MO2. Then add that executable to MO2 and use it as usual.

**Comment by klapperking** [comment]
Works like a charm, thank you!

I actually know that LoversLab post well but I didn't think it would work so I didn't bother to try... well.


TIL, even when it seems stupid - creating a folder in the Data Directoy seems to be a viable fix..

The same worked for getting Requiem to work... Creating an empty SkyProc Patchers folder and it magically works....

I need to start digging into the file path requirements apparently...

Anyways, thanks a lot! Cheers!!

**Comment by Problembeloeser** [comment]
@rockerbacon 
Would it maybe be possible to give more information about this fix on the README or a seperate Markdown file linked on it? I searched hours for a fix of this issue and only found this valid fix after coincidentally opening the closed issues page.

**Comment by rockerbacon** [comment]
> @rockerbacon
> Would it maybe be possible to give more information about this fix on the README or a seperate Markdown file linked on it? I searched hours for a fix of this issue and only found this valid fix after coincidentally opening the closed issues page.

I thought about documenting general tips, tricks and workarounds but it would be too much work for me to maintain on my own.

I gladly accept PRs, though. Anyone can add links to useful guides to the readme or push their own guides to the project.

**Comment by KorgiSilvercloud** [comment]
> Ran into the same problem, but it apparently isn't Linux. I'd link to the solution Forum, but it's on LoversLab.
> 
> You need to install just the FNIS executable into Skyrim's data folder, following the same directory structure in MO2. Then add that executable to MO2 and use it as usual.

I know this is an old report, but I am having the same issue and I for the life of me cannot solve it. I did as you said, and put the "GenerateFNISforusers.exe" files directly into my SkyrimSE data folder, but when trying to configure FNIS through the puzzle icon in MO2 I do not know how to tell it where that location is, since the wine window that pops up does not seem to identify the .steam folder.

**Comment by Problembeloeser** [comment]
> > Ran into the same problem, but it apparently isn't Linux. I'd link to the solution Forum, but it's on LoversLab.
> > You need to install just the FNIS executable into Skyrim's data folder, following the same directory structure in MO2. Then add that executable to MO2 and use it as usual.
> 
> I know this is an old report, but I am having the same issue and I for the life of me cannot solve it. I did as you said, and put the "GenerateFNISforusers.exe" files directly into my SkyrimSE data folder, but when trying to configure FNIS through the puzzle icon in MO2 I do not know how to tell it where that location is, since the wine window that pops up does not seem to identify the .steam folder.

You know where the .steam folder is located in your device. Just follow the absolute path, to which you can easily get through the wine file select window.

**Comment by KorgiSilvercloud** [comment]
> > > Ran into the same problem, but it apparently isn't Linux. I'd link to the solution Forum, but it's on LoversLab.
> > > You need to install just the FNIS executable into Skyrim's data folder, following the same directory structure in MO2. Then add that executable to MO2 and use it as usual.
> > 
> > 
> > I know this is an old report, but I am having the same issue and I for the life of me cannot solve it. I did as you said, and put the "GenerateFNISforusers.exe" files directly into my SkyrimSE data folder, but when trying to configure FNIS through the puzzle icon in MO2 I do not know how to tell it where that location is, since the wine window that pops up does not seem to identify the .steam folder.
> 
> You know where the .steam folder is located in your device. Just follow the absolute path, to which you can easily get through the wine file select window.

So after doing a little research, it seems my confusion was coming from the fact that the wine explorer just doesn't like to show hidden files for some reason. So I navigate to the exact location where my .steam folder should be within the wine explorer window...but it's just not there. Going into winecfg and ticking "show dot files" in the drives menu doesn't seem to fix it either, even though it seems like it very much should. So, failing that, how do you force wine to show you the hidden files you need to access?

**Comment by Problembeloeser** [comment]
Ohhh, I get 

> > > > Ran into the same problem, but it apparently isn't Linux. I'd link to the solution Forum, but it's on LoversLab.
> > > > You need to install just the FNIS executable into Skyrim's data folder, following the same directory structure in MO2. Then add that executable to MO2 and use it as usual.
> > > 
> > > 
> > > I know this is an old report, but I am having the same issue and I for the life of me cannot solve it. I did as you said, and put the "GenerateFNISforusers.exe" files directly into my SkyrimSE data folder, but when trying to configure FNIS through the puzzle icon in MO2 I do not know how to tell it where that location is, since the wine window that pops up does not seem to identify the .steam folder.
> > 
> > 
> > You know where the .steam folder is located in your device. Just follow the absolute path, to which you can easily get through the wine file select window.
> 
> So after doing a little research, it seems my confusion was coming from the fact that the wine explorer just doesn't like to show hidden files for some reason. So I navigate to the exact location where my .steam folder should be within the wine explorer window...but it's just not there. Going into winecfg and ticking "show dot files" in the drives menu doesn't seem to fix it either, even though it seems like it very much should. So, failing that, how do you force wine to show you the hidden files you need to access?

Oohh, I get your confusion now. Well, I cannot help you further, as my Skyrim Special Edition is installed into a non hidden folder on another drive. This issue seems to be beyond the scope of this project though, try asking at Wine for help, if you really do not wanna have Skyrim installed to a non hidden location

**Comment by rockerbacon** [comment]
> > > > Ran into the same problem, but it apparently isn't Linux. I'd link to the solution Forum, but it's on LoversLab.
> > > > You need to install just the FNIS executable into Skyrim's data folder, following the same directory structure in MO2. Then add that executable to MO2 and use it as usual.
> > > 
> > > 
> > > I know this is an old report, but I am having the same issue and I for the life of me cannot solve it. I did as you said, and put the "GenerateFNISforusers.exe" files directly into my SkyrimSE data folder, but when trying to configure FNIS through the puzzle icon in MO2 I do not know how to tell it where that location is, since the wine window that pops up does not seem to identify the .steam folder.
> > 
> > 
> > You know where the .steam folder is located in your device. Just follow the absolute path, to which you can easily get through the wine file select window.
> 
> So after doing a little research, it seems my confusion was coming from the fact that the wine explorer just doesn't like to show hidden files for some reason. So I navigate to the exact location where my .steam folder should be within the wine explorer window...but it's just not there. Going into winecfg and ticking "show dot files" in the drives menu doesn't seem to fix it either, even though it seems like it very much should. So, failing that, how do you force wine to show you the hidden files you need to access?

If you enter the hidden directory (".steam" in your case) in the textbox at the bottom and press enter it should open the directory and allow you to continue navigation.

**Comment by KorgiSilvercloud** [comment]
> > > > > Ran into the same problem, but it apparently isn't Linux. I'd link to the solution Forum, but it's on LoversLab.
> > > > > You need to install just the FNIS executable into Skyrim's data folder, following the same directory structure in MO2. Then add that executable to MO2 and use it as usual.
> > > > 
> > > > 
> > > > I know this is an old report, but I am having the same issue and I for the life of me cannot solve it. I did as you said, and put the "GenerateFNISforusers.exe" files directly into my SkyrimSE data folder, but when trying to configure FNIS through the puzzle icon in MO2 I do not know how to tell it where that location is, since the wine window that pops up does not seem to identify the .steam folder.
> > > 
> > > 
> > > You know where the .steam folder is located in your device. Just follow the absolute path, to which you can easily get through the wine file select window.
> > 
> > 
> > So after doing a little research, it seems my confusion was coming from the fact that the wine explorer just doesn't like to show hidden files for some reason. So I navigate to the exact location where my .steam folder should be within the wine explorer window...but it's just not there. Going into winecfg and ticking "show dot files" in the drives menu doesn't seem to fix it either, even though it seems like it very much should. So, failing that, how do you force wine to show you the hidden files you need to access?
> 
> If you enter the hidden directory (".steam" in your case) in the textbox at the bottom and press enter it should open the directory and allow you to continue navigation.

That does not work either, it only lets you enter a specific file name in that text box not folders. I decided to follow Problembeloeser's advice though and created a seperate steam library exclusively for SkyrimSE and pointed MO2 to that instead. doing so allowed me to finally be able to select the "GenerateFNISforusers" executable within my skyrimSE installation directory, and properly run FNIS. Since there seems to be an issue with wine not being able to identify . files, it may be a good idea to suggest that people install SkyrimSE outside of the tradition .steam folder that it wants to install into by default.

**Comment by loho97** [comment]
> @rockerbacon Would it maybe be possible to give more information about this fix on the README or a seperate Markdown file linked on it? I searched hours for a fix of this issue and only found this valid fix after coincidentally opening the closed issues page.

After some trial and error, it seems I have figured it out. 

After installing FNIS through MO2, as I would do with any mod, I located GenerateFNISforUsers.exe in
`/home/user/Games/mod-organizer-2-skyrimspecialedition/modorganizer2/mods/Fores New Idles in Skyrim SE - FNIS SE/tools/GenerateFNIS_for_Users`

then I copied GenerateFNISforUsers.exe to
`/home/user/.local/share/Steam/steamapps/common/Skyrim Special Edition/Data/tools/GenerateFNIS_for_Users/GenerateFNISforUsers.exe`

then, In MO2, I edited the FNIS executable. My "Binary" path was set to 
Z:\home\user\.local\share\Steam\steamapps\common\Skyrim Special Edition\Data\tools\GenerateFNIS_for_Users\GenerateFNISforUsers.exe

my "Start in" path was set to 
Z:\home\user\Games\mod-organizer-2-skyrimspecialedition\modorganizer2\mods\Fores New Idles in Skyrim SE - FNIS SE\tools\GenerateFNIS_for_Users
