### ISSUE TITLE
Doesn't find games installed via steam flatpak

### ISSUE THREAD

**Issue by stobbsm** [rockerbacon/lutris-skyrimse-installers#62]
Trying to use Mod-organizer-2 with a flatpak installed version of any supported game fails with the game not being found, even though it is installed.

**Expected**: That the flatpak library is searched for the given game.

**Actual**: Fails to find the installed game

**Workaround**: Tried symlinking folders to the correct location with no joy.-

**Comment by rockerbacon** [comment]
Flatpak is not officially supported. As a temporary solution you can link the database where Steam lists libraries to the expected location:

1. Locate the Flatpak Steam installation in `$HOME/.local/share/flatpak/app`
2. Locate the file `libraryfolders.vdf` inside `current/steam/steamapps`
3. Link this file to `$HOME/.steam/steam/steamapps/libraryfolders.vdf`
