### ISSUE TITLE
Oblivion Testing

### ISSUE THREAD

**Issue by VagabondAzulien** [rockerbacon/lutris-skyrimse-installers#63]
First: thank you for this script.

I am working on getting Oblivion working with mods using Mod Organizer 2. It appears to be completely untested as of yet. As per the README, I am opening an issue to track any progress.

## System
Arch Linux, kernel 5.6.14-arch1-1
Intel i5-6500 3.2GHz
NVIDIA GeForce GTX 1060 6GP, drivers version 440.82-17
16GB Ram

Game is installed on an SSD.
Steam version 1.0.0.62-1
Proton version 5.0-7

## Tested
- Installing Mod Manager 2 and OBSE via this script :heavy_check_mark: 
- Manually downloading and installing a mod from Nexus :heavy_check_mark: 
- Running Oblivion through Mod Manager 2 with no mods :warning:
- Running Oblivion through Mod Manager 2 with mods :warning:

## Results
Installation went smooth, after #61 was resolved. Had to set arguments due to my Steam library not being at the default location (`--proton-libdir /path/to/Steam/dir`). Once installed, tried running Oblivion without mods and the game started. Exited at main menu, downloaded a few mods, and tried again. Game started successfully, with modifications apparent (DarNified UI, specifically). Once confirmed game works with and without mods, jumped into starting a new game. Immediately noticed performance issues. After about 5 minutes, game freezes. Tested both with and without mods; same results. I believe there's a memory leak, perhaps tied to OBSE. I confirmed no performance problems when running the game from Steam directly (using the same Proton versions).

I will continue to investigate. I have no experience with OBSE, Mod Manager, or Lutris. I have limited experience with performance testing. Any suggestions welcomed.

**Comment by rockerbacon** [comment]
You said you think the problem might be related to OBSE. Do you experience the problem if you run Oblivion from within Mod Manager instead of OBSE?

**Comment by VagabondAzulien** [comment]
Selecting `Oblivion` instead of `OBSE`, then clicking "Run", I experience the same problems: performance drop, as well as freezing after roughly 5 minutes. One other thing I just noticed: I don't think running it through Mod Organizer plays any of the music. All other sound seems to work fine though.

**Comment by rockerbacon** [comment]
Exit Steam and start it in debug mode with the following command:

```
PROTON_DUMP_DEBUG_COMMANDS=1 steam
```

This will create a directory containing debug data in `/tmp/${USER}_proton`, send me the contents of the `run` file. This should allow me to check for differences between the Lutris launcher and Steam.

**Comment by VagabondAzulien** [comment]
Here's the `gdb_run` file: https://gist.github.com/VagabondAzulien/cc42446174b36733b500184499690a0d

**Comment by VagabondAzulien** [comment]
Additionally, here are the logs from my recent run of Mod Manager, using the `OBSE` run option: https://gist.github.com/VagabondAzulien/088c86167abf5500c15d4a5be352566a

**Comment by rockerbacon** [comment]
> Here's the `gdb_run` file: https://gist.github.com/VagabondAzulien/cc42446174b36733b500184499690a0d

From these logs I see that your Steam Client was installed to a different path than the expected one (`$HOME/.local/share/Steam` instead of `$HOME/.steam`), this is breaking the creation of `LD_LIBRARY_PATH` in the launcher script because of bug #72. When the mentioned bug is fixed, so should these problems.

**Comment by VagabondAzulien** [comment]
I can confirm that after manually overriding the `LD_LIBRARY_PATH` in the `run_proton` configuration that things seem to be performing much better: the game runs without the performance issues, and the music works.

I literally took the `LD_LIBRARY_PATH` from the gdb file above and replaced the library path in `proton-launcher.sh`. I haven't tried to construct it from other variables/information.

**Comment by rockerbacon** [comment]
[Release 2.7.1](https://github.com/rockerbacon/lutris-skyrimse-installers/releases/tag/2.7.1) should have fixed all instability problems.

All that's left is to confirm whether or not ENB works. Have you tried that?

**Comment by VagabondAzulien** [comment]
I haven't tried ENB, nor had I intentions to. Looking into it briefly, it seems that ENB isn't very well supported for Oblivion to begin with. If I get some free time, I'll give it a shot.

As for additional mods, I've mostly had success. I've had problems with a mod called MenuQue working properly, and am looking into it. Been a bit busy though, so testing is slow.

**Comment by VagabondAzulien** [comment]
Getting MenuQue to work required a small modification: 

- Go to `Tools` -> `Executables`
- Modify `Oblivion`, and select the `Force load libraries (*)` option.
- Click the `Configure Libraries` button
- Assuming there are no entries: click `Add Row`:
    - In the first box, select the executable for Oblivion (probably just `Oblivion.exe`)
    - In the second box, select the DLL file for OBSE (probably `obse_1_2_416.dll`)
    - Finally, make sure the checkbox to the left is checked.
- Click OK, then Apply, and exit out.

Moving forward, run the `Oblivion` option and _not_ the `OBSE` option.

**Comment by rockerbacon** [comment]
Readme updated to contain new information
