### ISSUE TITLE
vcrun2019 sha256sum mismatch

### ISSUE THREAD

**Issue by brandonegbert** [rockerbacon/lutris-skyrimse-installers#64]
`sha256sum mismatch! Rename /home/$user/.cache/winetricks/vcrun2019/vc_redist.x86.exe and try again.`

I repeatedly get that failure trying to setup Fallout 4 with Steamplay.  Maybe MS updated the executable?

**Comment by brandonegbert** [comment]
Looks like this is probably a winetricks issue.

**Comment by brandonegbert** [comment]
`sudo winetricks --self-update` fixes it it seems.  Make sure you're not in a git dir when you run it or it'll think you're in a dev environment.

**Comment by rockerbacon** [comment]
See #61
