### ISSUE TITLE
Instal problem

### ISSUE THREAD

**Issue by ebitnet65** [rockerbacon/lutris-skyrimse-installers#65]
The installation exits with an error:
_I can't move ~/.cache/lutris/installer/mod-organizer-2/successful-prefix-preparation, it does not exist_

Failed to load module "appmenu-gtk-module"

clues?

thanks

**Comment by rockerbacon** [comment]
Please post the entire output of the terminal

**Comment by Zouizoui78** [comment]
Hello, same problem here when installing mod organizer 2 for Skyrim SE. Issue seems to happen during/after vrun2019 install with winetricks. Here is the log : https://pastebin.com/rFWmkLbK

**Comment by rockerbacon** [comment]
> Hello, same problem here when installing mod organizer 2 for Skyrim SE. Issue seems to happen during/after vrun2019 install with winetricks. Here is the log : https://pastebin.com/rFWmkLbK

Check #61

**Comment by Zouizoui78** [comment]
Fixed ! Definitely an issue on winetricks' end. Thanks for your help.

**Comment by ebitnet65** [comment]
Thanks! The info in #64 appeared to have worked.
