### ISSUE TITLE
Installation stuck at extracting

### ISSUE THREAD

**Issue by dlbt96** [rockerbacon/lutris-skyrimse-installers#74]
Actually I'm experiencing many problems installing MO2 for Skyrim. Sometimes I can install it but it simply does not run. When I try to install it again, it stucks at extracting something, can be openjdk or f4se, or skse. I'm using Ubuntu 20.04. The log looks normal, saying everything is ok but it simply hangs at extracting. I left it running for a whole night but still. Please tell me if you need any more info/logs. Thank you.

`lutris -i "$HOME/Games/modorganizer2.yml" 
2020-06-03 08:46:13,773: Running Lutris 0.5.6
2020-06-03 08:46:13,774: Using NVIDIA drivers 440.64 for x86_64
2020-06-03 08:46:13,774: GPU: GeForce GTX 1050
2020-06-03 08:46:13,774: GPU: 10DE:1C8D 1028:0798 using nvidia drivers
2020-06-03 08:46:13,774: GPU: 8086:591B 1028:0798 using i915 drivers
2020-06-03 08:46:13,840: Vulkan is supported
2020-06-03 08:46:13,841: Updating DXVK versions
2020-06-03 08:46:18,918: Downloading file 1 of 16
2020-06-03 08:46:19,425: Downloading file 2 of 16
2020-06-03 08:46:19,930: Downloading file 3 of 16
2020-06-03 08:46:20,435: Downloading file 4 of 16
2020-06-03 08:46:20,940: Downloading file 5 of 16
2020-06-03 08:46:21,446: Downloading file 6 of 16
2020-06-03 08:46:21,952: Downloading file 7 of 16
2020-06-03 08:46:22,457: Downloading file 8 of 16
2020-06-03 08:46:24,467: Downloading file 9 of 16
2020-06-03 08:46:24,973: Downloading file 10 of 16
2020-06-03 08:46:25,479: Downloading file 11 of 16
2020-06-03 08:46:25,984: Downloading file 12 of 16
2020-06-03 08:46:28,495: Downloading file 13 of 16
2020-06-03 08:46:29,000: Downloading file 14 of 16
2020-06-03 08:46:29,506: Downloading file 15 of 16
2020-06-03 08:46:30,012: Downloading file 16 of 16

(lutris:16205): Gtk-CRITICAL **: 08:46:41.101: gtk_tree_model_get_column_type: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed

(lutris:16205): Gtk-CRITICAL **: 08:46:41.101: gtk_combo_box_get_active_id: assertion 'gtk_tree_model_get_column_type (model, column) == G_TYPE_STRING' failed
Running /usr/bin/bash -c xdg-mime default modorganizer2-nxm-handler.desktop x-scheme-handler/nxm
Initial process has started with pid 16300
Game is considered started.
Game is considered exited.
Initial process has exited.
All children have exited.
Exit with returncode 0

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 37319384 bytes (36 MiB)                           

Extracting archive: /home/bathong/Games/MO2/mod-organizer-2/openjdk/OpenJDK8U-jre_x64_windows_8u252b09.zip
--
Path = /home/bathong/Games/MO2/mod-organizer-2/openjdk/OpenJDK8U-jre_x64_windows_8u252b09.zip
Type = zip
Physical Size = 37319384

Everything is Ok                                    

Folders: 15
Files: 121
Size:       94859720
Compressed: 37319384

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 384875 bytes (376 KiB)                         

Extracting archive: /home/bathong/Games/MO2/mod-organizer-2/fose/fose_v1_2_beta2.7z
--
Path = /home/bathong/Games/MO2/mod-organizer-2/fose/fose_v1_2_beta2.7z
Type = 7z
Physical Size = 384875
Headers Size = 3155
Method = LZMA:6m BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 8
Files: 184
Size:       4753751
Compressed: 384875

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 598435 bytes (585 KiB)                         

Extracting archive: /home/bathong/Games/MO2/mod-organizer-2/f4se/f4se_0_06_21.7z
--
Path = /home/bathong/Games/MO2/mod-organizer-2/f4se/f4se_0_06_21.7z
Type = 7z
Physical Size = 598435
Headers Size = 5414
Method = LZMA2:22 LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 14
Files: 393
Size:       3284040
Compressed: 598435

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 712979 bytes (697 KiB)                         

Extracting archive: /home/bathong/Games/MO2/mod-organizer-2/nvse/nvse_5_1_beta4.7z
--
Path = /home/bathong/Games/MO2/mod-organizer-2/nvse/nvse_5_1_beta4.7z
Type = 7z
Physical Size = 712979
Headers Size = 4131
Method = LZMA2:6m LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 12
Files: 231
Size:       4902927
Compressed: 712979

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 4079213 bytes (3984 KiB)                       

Extracting archive: /home/bathong/Games/MO2/mod-organizer-2/mwse/mwse.zip
--
Path = /home/bathong/Games/MO2/mod-organizer-2/mwse/mwse.zip
Type = zip
Physical Size = 4079213

Everything is Ok

Folders: 23
Files: 127
Size:       14114269
Compressed: 4079213

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 1662426 bytes (1624 KiB)                       

Extracting archive: /home/bathong/Games/MO2/mod-organizer-2/obse/obse_0021.zip
--
Path = /home/bathong/Games/MO2/mod-organizer-2/obse/obse_0021.zip
Type = zip
Physical Size = 1662426
Comment = ; WinRAR
; Multifunctional Integrated Archive Manager

Everything is Ok

Folders: 12
Files: 342
Size:       6092629
Compressed: 1662426
Running /usr/bin/bash -c printf '\x90\x90\x90' | dd conv=notrunc of='/home/bathong/.cache/lutris/installer/mod-organizer-2/oblivion-script-extender/obse_loader.exe' bs=1 seek=$((0x14cb))
Initial process has started with pid 16375
Game is considered started.
3+0 records in
3+0 records out
3 bytes copied, 3.3261e-05 s, 90.2 kB/s
Game is considered exited.
Initial process has exited.
All children have exited.
Exit with returncode 0

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 624845 bytes (611 KiB)                         

Extracting archive: /home/bathong/Games/MO2/mod-organizer-2/skse/skse_1_07_03.7z
--
Path = /home/bathong/Games/MO2/mod-organizer-2/skse/skse_1_07_03.7z
Type = 7z
Physical Size = 624845
Headers Size = 8072
Method = LZMA2:22 LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 14
Files: 544
Size:       3591799
Compressed: 624845

`

**Comment by rockerbacon** [comment]
If that's the complete log, you should take this issue to the [Lutris project](https://github.com/lutris/lutris). The installer uses the builtin download and extract methods provided by Lutris.
