### ISSUE TITLE
Can't run SkyProc patch

### ISSUE THREAD

**Issue by dlbt96** [rockerbacon/lutris-skyrimse-installers#75]
I'm trying to run a SkyProc patch using C:\java\bin\java.exe from MO2. Although it does launch, the screen stutters and I can't click anything.
It looks like this.
![image](https://user-images.githubusercontent.com/42767321/83712547-06a06680-a5f4-11ea-9ae4-ddf61e74d092.png)

**Comment by rockerbacon** [comment]
See #42
