### ISSUE TITLE
New Vegas Testing

### ISSUE THREAD

**Issue by Mihli** [rockerbacon/lutris-skyrimse-installers#78]
Archlinux, 5.7.0-arch1-1-pds
Intel i7-4790k, R9 390, 8GB ram
mesa-git, AMDGPU
steam version

Runs well with mods, and latest ENB in fullscreen, haven't gone far in game but havn't had any crashing or broken areas. setting to windowed in launcher gives renderer error, but ENB can probably take care of windowing. Mouse speed is different in some menus and seems to warp a bit in pip-boy(this may just be a readius mod thing); I hadn't opened the normal pipboy at any time. The first loading screen takes longer than normal with ENB running but afterwords speeds are normal for NV on an SSD.

edit: all menus seem to have the mouse issue

**Comment by rockerbacon** [comment]
Readme updated to contain new information.

Mouse issue will be treated separately.
