### ISSUE TITLE
Skyrim SE, arch linux issue?

### ISSUE THREAD

**Issue by Desulate** [rockerbacon/lutris-skyrimse-installers#90]
It seems to fail with Skyrim SE.

Launching it via MO2 fails stating `Application load error 3:0000065432`, trying via steam with the skse64 launcher fails where it launches but simply has no mods enabled but the game otherwise works.

------

Updating FNIS also showed issues, but was removed during my attempts to use MO2 since it was throwing errors. 

```
>>Warning: Expected generator path: Z:\home\sn\Games\Steam\steamapps\common\Skyrim Special Edition\data\tools\GenerateFNIS_for_Users not found<<
```

```
ERROR(2012): Could not generate: defaultfemale.hkx defaultmale.hkx weapequip.hkx staggerbehavior.hkx sprintbehavior.hkx shout_behavior.hkx magicmountedbehavior.hkx magicbehavior.hkx magic_readied_direction_behavior.hkx 1hm_locomotion.hkx 1hm_behavior.hkx 0_master.hkx 
```

**Comment by rockerbacon** [comment]
I could not reproduce the issue, Skyrim Special Edition launches just fine on my machine. What distro are you using?

See #57 for the FNIS error.

**Comment by Desulate** [comment]
Im using arch linux

**Comment by kleshas** [comment]
The generator path is because you need to copy the FNIS install folder to /Data/Tools in your SkyrimSE install path and run GenerateFNISforUsers.exe from there via a shortcut in MO2. (Z:\mnt\veracrypt3\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\tools\GenerateFNIS_for_Users\GenerateFNISforUsers.exe for me)

The FNIS error is because you didn't check the HKX checkbox beneath the Skeleton Arm Fix in FNIS.

I run arch too, came across both these issues this past week during a new modded setup :)

**Comment by Desulate** [comment]
So I just need to figure out what is causing the `Application load error 3:0000065432` still.

**Comment by kleshas** [comment]
First response on googling that is a suggestion to try verifying the game files - in steam, properties of SkyrimSE, local files tab, Verify Integrity... button.  Using MO2, the base Skyrim SE files should be vanilla anyways, so this should be fine.

**Comment by desilver** [comment]
The issue isn't arch-linux exclusive, had the same one on new setup ubuntu 20.04 env.
The hint to copy the .exe directly into the game folder works well for me ... thx @kleshas

**Comment by rockerbacon** [comment]
For Arch, update [2.7.5](https://github.com/rockerbacon/lutris-skyrimse-installers/releases/tag/2.7.5) might do the trick.

**Comment by Desulate** [comment]
Well when I logged in to try you suggestions I was in for some fun lol.

First I ran into the vc_redist issue.

Now the install can seem to locate wine-mono even though it is definitely installed, winetricks in general seems to be shaky on arch for these installs. It just says to start steam even though it is started and then fails to load, so unfortunately i haven't tried what @kleshas suggested yet. 

[Output](https://pastebin.com/fyGUfQnt) while installing 2.8.2 Stable

I'll try update 2.7.5 next, maybe its just 2.8.2 issue

**Comment by Desulate** [comment]
With 2.7.5 I think I'm getting [errors](https://pastebin.com/Sswe4MHB) for fontconfig.

```
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig warning: line 9: unknown element "description"
```

I found a related [arch bug](https://bbs.archlinux.org/viewtopic.php?id=235643) from 2018, but it wasn't an issue before with 2.7.4 Stable or anything else I've installed with wine or lutis and I've had a clean install since that bug was supposedly fixed.

**Comment by rockerbacon** [comment]
@Desulate try deleting compatdata for SkyrimSE and launching it on Steam again.

The compatdata can be found at `path/to/steam/library/steamapps/compatdata/489830`. If you don't know the path to the Steam library then it's probably `$HOME/.steam/root/steam`.

**Comment by rockerbacon** [comment]
@Desulate you might be on the same situation as the one solved here [here](https://github.com/rockerbacon/lutris-skyrimse-installers/issues/91#issuecomment-651286690)

**Comment by Desulate** [comment]
This hasn't seemed to fix it for me yet. 

I'm going to try to completely remove wine, winetricks, steam, skyrim and lutris then reinstall them. If there is any compdata delete it again and update vc-redist / winetricks again if I need to then get back to you, just to make sure.

**Comment by Desulate** [comment]
Unfortunately it had no effect on the fontconfig issue.

**Comment by Desulate** [comment]
Its likely this is still a possible issue on arch.

However I've switched distros for unrelated reasons. I'm closing this issue for now.

**Comment by Celti** [comment]
I was having this same issue with Fallout 4 on latest Arch, fixed by launching with `--system-libs`.
