### ISSUE TITLE
I'm stuck at "Executing mkdir -p /home/---/.steam/steam/steamapps/compatdata/489830"

### ISSUE THREAD

**Issue by Merhern** [rockerbacon/lutris-skyrimse-installers#96]
I tried both Skyrim SE and old Skyrim and neither works.

**Comment by rockerbacon** [comment]
This command is executed by Winetricks, which currently has a bug. Check #61 to see if that's your issue

**Comment by rockerbacon** [comment]
Closed due to inactivity

**Comment by KiviTK** [comment]
I am having the same issue and I did check #61 and that is not my issue, I have fixed everything winetricks related by following the resolution on #158
