### ISSUE TITLE
"Failed to initialize renderer. Unknown error creating the Gamebryo renderer" [Fallout New Vegas]

### ISSUE THREAD

**Issue by KorgiSilvercloud** [rockerbacon/lutris-skyrimse-installers#99]
So, after my overall success with getting Fallout 4 up and running with this installer I tried New Vegas next. Everything seems to have installed properly, however when I chose to run NVSE in my MO2 window, a black screen pops up immediately with that error in the title. upon clicking the error window, the game immediately shuts down. The game will launch properly directly through steam.

**Comment by rockerbacon** [comment]
Try the following:

- Run it without any plugins or ENBs
- Ensure the game is configured to run in fullscreen

**Comment by KorgiSilvercloud** [comment]
That fixed it, thank you. I was trying to run the game in windowed mode.

**Comment by rockerbacon** [comment]
Readme was updated to inform the game only works in fullscreen.

**Comment by MissLav** [comment]
> Readme was updated to inform the game only works in fullscreen.

only issue with this is that if u alt tab you cant reopen the game
